export const EBAY_SELLER_RUNTIME_DATA_RESOLVER_RUN_VERSION="EBAY_SELLER_RUNTIME_DATA_RESOLVER_RUN_B2_RUN_V1"
type Row=Record<string,unknown>; type Fixture=Row&{selectedProduct?:Row;localConfirmedRuntimeData?:Row;forbiddenActions?:unknown[];allowedActionsThisLoop?:unknown[];safetyFlags?:Record<string,boolean>}
export type ResolverRunSimulation={localConfirmationPhrase?:string;categoryConfirmed?:boolean;fulfillmentConfirmed?:boolean;returnConfirmed?:boolean;paymentConfirmed?:boolean;stockConfirmed?:boolean;priceConfirmed?:boolean;imageConfirmed?:boolean;environmentConfirmed?:boolean;tokenPresenceChecked?:boolean;tokenPresentBooleanOnly?:boolean;simulatedStock?:number;simulatedPrice?:number}
const text=(v:unknown,f="")=>typeof v==="string"&&v.length?v:f; const num=(v:unknown,f=0)=>{const n=typeof v==="number"?v:Number(v);return Number.isFinite(n)?n:f}; const rec=(v:unknown):Row=>v!==null&&typeof v==="object"&&!Array.isArray(v)?v as Row:{}; const yes=(v:unknown)=>v===true
export function buildEbaySellerRuntimeDataResolverRunInput(f:Fixture,s:ResolverRunSimulation={}){return{version:text(f.version,EBAY_SELLER_RUNTIME_DATA_RESOLVER_RUN_VERSION),status:text(f.status),sourceRoute:text(f.sourceRoute),defaultMode:text(f.defaultMode,"SAFE_NO_RUNTIME_READ"),selectedProduct:f.selectedProduct??{},data:f.localConfirmedRuntimeData??{},exactLocalConfirmationPhrase:text(f.exactLocalConfirmationPhrase),forbidden:Array.isArray(f.forbiddenActions)?f.forbiddenActions.map(String):[],allowed:Array.isArray(f.allowedActionsThisLoop)?f.allowedActionsThisLoop.map(String):[],simulation:s}}
export function validateLocalRuntimeConfirmationPhrase(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){const accepted=typeof i.simulation.localConfirmationPhrase==="string"&&i.simulation.localConfirmationPhrase===i.exactLocalConfirmationPhrase;return{localConfirmationPhraseAccepted:accepted}}
export function buildRuntimeCategoryResolutionAssessment(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){const ok=yes(i.simulation.categoryConfirmed);return{categoryIdStatus:ok?"CONFIRMED":"PENDING",categoryResolved:ok}}
export function buildRuntimeSellerPolicyResolutionAssessment(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){const f=yes(i.simulation.fulfillmentConfirmed),r=yes(i.simulation.returnConfirmed),p=yes(i.simulation.paymentConfirmed);return{fulfillmentPolicyStatus:f?"CONFIRMED":"PENDING",returnPolicyStatus:r?"CONFIRMED":"PENDING",paymentPolicyStatus:p?"CONFIRMED":"PENDING",fulfillmentResolved:f,returnResolved:r,paymentResolved:p,policiesResolved:f&&r&&p}}
export function buildRuntimeStockResolutionAssessment(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){const configured=rec(i.data.finalStock),stock=i.simulation.simulatedStock===undefined?num(configured.value):num(i.simulation.simulatedStock);const ok=yes(i.simulation.stockConfirmed)&&stock>0;return{finalStockStatus:ok?"CONFIRMED":yes(i.simulation.stockConfirmed)?"BLOCKED":"PENDING",stockResolved:ok,finalStock:stock}}
export function buildRuntimePriceResolutionAssessment(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){const configured=rec(i.data.finalPrice),price=i.simulation.simulatedPrice===undefined?num(configured.value):num(i.simulation.simulatedPrice);const ok=yes(i.simulation.priceConfirmed)&&price>0;return{finalPriceStatus:ok?"CONFIRMED":yes(i.simulation.priceConfirmed)?"BLOCKED":"PENDING",priceResolved:ok,finalPrice:price}}
export function buildRuntimeImageAssetResolutionAssessment(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){const ok=yes(i.simulation.imageConfirmed);return{finalImageAssetStatus:ok?"CONFIRMED_OR_BYPASSED_FOR_UNPUBLISHED_ONLY":"PENDING",imageResolved:ok,imageGenerationUsed:false,imageDownloadUsed:false,imageCopyAllowed:false}}
export function buildRuntimeEnvironmentResolutionAssessment(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){const ok=yes(i.simulation.environmentConfirmed);return{targetEnvironmentStatus:ok?"CONFIRMED":"PENDING",environmentResolved:ok,targetEnvironment:ok?"SANDBOX":null}}
export function buildRuntimeTokenPresenceBooleanAssessment(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){const checked=yes(i.simulation.tokenPresenceChecked),present=checked&&yes(i.simulation.tokenPresentBooleanOnly);return{tokenPresenceChecked:checked,tokenPresentBooleanOnly:present,tokenStored:false,tokenPrinted:false}}
export function buildLocalConfirmedRuntimeDataAssessment(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){return{...buildRuntimeCategoryResolutionAssessment(i),...buildRuntimeSellerPolicyResolutionAssessment(i),...buildRuntimeStockResolutionAssessment(i),...buildRuntimePriceResolutionAssessment(i),...buildRuntimeImageAssetResolutionAssessment(i),...buildRuntimeEnvironmentResolutionAssessment(i),...buildRuntimeTokenPresenceBooleanAssessment(i)}}
export function buildNoWriteRuntimeResolverGuard(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){const forbidden=["createOrReplaceInventoryItem","createOffer","publishOffer","publish","createActiveListing","reviseActiveListing","bulkPublish"].every(x=>i.forbidden.includes(x));const safe=new Set(["buildLocalRuntimeResolutionChecklist","acceptLocalRuntimeConfirmations","tokenPresenceBooleanCheck","optionalFutureReadOnlySellerPolicyLookup","readinessReportOnly"]);return{noWriteGuardPassed:forbidden&&i.allowed.every(x=>safe.has(x)),publishOfferForbidden:forbidden,canExecuteEbayWrite:false,canPublish:false}}
export function buildRuntimeResolverRunGate(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){const phrase=validateLocalRuntimeConfirmationPhrase(i),a=buildLocalConfirmedRuntimeDataAssessment(i);const items=[a.categoryResolved,a.fulfillmentResolved,a.returnResolved,a.paymentResolved,a.stockResolved,a.priceResolved,a.imageResolved,a.environmentResolved];return{...phrase,...a,runtimeDataResolvedCount:items.filter(Boolean).length,runtimeDataRequiredCount:8,runtimeDataAllResolved:items.every(Boolean),controlledDraftOnlyRunReady:phrase.localConfirmationPhraseAccepted&&items.every(Boolean)&&a.tokenPresentBooleanOnly}}
export function buildControlledDraftOnlyRunReadiness(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){return{...buildRuntimeResolverRunGate(i),...buildNoWriteRuntimeResolverGuard(i),canExecuteEbayWrite:false,canPublish:false}}
export function buildSellerRuntimeDataResolverRunRouteRecommendation(i:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunInput>){const g=buildRuntimeResolverRunGate(i);let route="READY_FOR_CONTROLLED_DRAFT_ONLY_REAL_RUN";if(!g.localConfirmationPhraseAccepted)route="NEED_LOCAL_RUNTIME_CONFIRMATION";else if(!g.categoryResolved)route="NEED_CATEGORY_RUNTIME_CONFIRMATION";else if(!g.policiesResolved)route="NEED_SELLER_POLICY_RUNTIME_CONFIRMATION";else if(!g.stockResolved)route="NEED_FINAL_STOCK_REVIEW";else if(!g.priceResolved)route="NEED_FINAL_PRICE_REVIEW";else if(!g.imageResolved)route="NEED_FINAL_IMAGE_ASSET";else if(!g.environmentResolved)route="NEED_RUNTIME_ENVIRONMENT";else if(!g.tokenPresentBooleanOnly)route="NEED_RUNTIME_EBAY_ACCESS_TOKEN";return{nextRecommendedRoute:route}}
export function buildEbaySellerRuntimeDataResolverRunReport(f:Fixture,s:ResolverRunSimulation={}){const i=buildEbaySellerRuntimeDataResolverRunInput(f,s);return{sellerRuntimeDataResolverRunReportBuilt:true,mode:validateLocalRuntimeConfirmationPhrase(i).localConfirmationPhraseAccepted?"LOCAL_CONFIRMED_RUNTIME_DATA":"SAFE_NO_RUNTIME_READ",selectedProductSku:text(i.selectedProduct.sku),selectedProductTitle:text(i.selectedProduct.title),...buildControlledDraftOnlyRunReadiness(i),...buildSellerRuntimeDataResolverRunRouteRecommendation(i),realEbayApiUsed:false,ebayWriteApiUsed:false,realEbayWriteExecuted:false,draftCreated:false,inventoryItemCreated:false,offerCreated:false,listingCreated:false,publicationExecuted:false,tokenExchangeExecuted:false,tokenStored:false,tokenPrinted:false,productionWriteTouched:false,mainTouched:false,stagingWriteExecuted:false,supabaseWriteExecuted:false,imageGenerationUsed:false,imageDownloadUsed:false,imageCopyAllowed:false,scraperUsed:false,amazonTrackTouched:false,whatsappRealSendUsed:false,smsRealSendUsed:false,openAiUsed:false,fullWarehouseStreetAddressCommitted:false,canExecuteEbayWrite:false,canPublish:false}}
export function summarizeEbaySellerRuntimeDataResolverRun(r:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunReport>){const k=["sellerRuntimeDataResolverRunReportBuilt","mode","selectedProductSku","selectedProductTitle","localConfirmationPhraseAccepted","categoryIdStatus","fulfillmentPolicyStatus","returnPolicyStatus","paymentPolicyStatus","finalStockStatus","finalPriceStatus","finalImageAssetStatus","targetEnvironmentStatus","tokenPresenceChecked","tokenPresentBooleanOnly","tokenStored","tokenPrinted","runtimeDataResolvedCount","runtimeDataRequiredCount","runtimeDataAllResolved","controlledDraftOnlyRunReady","canExecuteEbayWrite","canPublish","realEbayWriteExecuted","nextRecommendedRoute"] as const;return Object.fromEntries(k.map(x=>[x,r[x]]))}
export function getEbaySellerRuntimeDataResolverRunChecklist(r:ReturnType<typeof buildEbaySellerRuntimeDataResolverRunReport>){return[{id:"eight",passed:r.runtimeDataRequiredCount===8},{id:"token",passed:!r.tokenStored&&!r.tokenPrinted},{id:"no-write",passed:!r.canExecuteEbayWrite&&!r.canPublish&&!r.realEbayWriteExecuted}]}
