export const SELLER_OS_CROSS_PHASE_SHARED_FOUNDATION_VERSION =
  "W0_CROSS_PHASE_SHARED_FOUNDATION_V1" as const
export const SELLER_OS_CROSS_PHASE_REUSE_MAP_VERSION =
  "SELLER_OS_CROSS_PHASE_REUSE_MAP_V1" as const
export const SELLER_OS_CROSS_PHASE_REUSE_POLICY_VERSION =
  "SELLER_OS_CROSS_PHASE_REUSE_POLICY_V1" as const

export const SELLER_OS_CROSS_PHASE_CLASSIFICATIONS_V1 = Object.freeze([
  "REUSE_AS_IS",
  "EXTEND_CANONICAL",
  "NEW_SHARED_CAPABILITY",
  "DOMAIN_SPECIFIC",
  "DUPLICATE_TO_REMOVE",
] as const)

export const SELLER_OS_ROADMAP_PHASES_V1 = Object.freeze([
  "PHASE_1_SALES_ORDERS_ALERTS_WHATSAPP_THANK_YOU",
  "PHASE_2_LUNA_STOCK_AUTOMATION",
  "PHASE_3_COMMERCIAL_DECISION_LOOP",
  "PHASE_4_AUTOMATION_OPERATING_MODEL",
  "PHASE_5_EXPERIMENTS",
  "PHASE_6_ECONOMICS",
  "PHASE_6B_LUNA_PROCUREMENT_FULFILLMENT_AUTOMATION",
  "PHASE_7_EBAY_QUALITY_OPPORTUNITIES",
  "PHASE_8_LEARNING",
  "PHASE_9_PORTFOLIO_INTELLIGENCE",
  "PHASE_10_COMMERCIAL_INTELLIGENCE_PRODUCT_CASE_BRIDGE",
] as const)

type ClassificationV1 = typeof SELLER_OS_CROSS_PHASE_CLASSIFICATIONS_V1[number]
type RoadmapPhaseV1 = typeof SELLER_OS_ROADMAP_PHASES_V1[number]

type ReuseEntryV1 = Readonly<{
  capability: string
  responsibility: string
  canonicalOwner: string
  canonicalImplementation: readonly string[]
  currentConsumers: readonly string[]
  futureConsumers: readonly RoadmapPhaseV1[]
  classification: ClassificationV1
  contractVersion: string | null
  extensionPolicy: string
  safetyClass: string
  sideEffectClass: string
  deprecationStatus: "ACTIVE" | "DEPRECATE_AFTER_CONSUMER_MIGRATION" |
    "CONTRACT_ONLY_IMPLEMENTATION_DEFERRED"
  limitations: readonly string[]
}>

function entry(value: ReuseEntryV1) {
  return Object.freeze({ ...value,
    canonicalImplementation: Object.freeze([...value.canonicalImplementation]),
    currentConsumers: Object.freeze([...value.currentConsumers]),
    futureConsumers: Object.freeze([...value.futureConsumers]),
    limitations: Object.freeze([...value.limitations]),
  })
}

const P1 = SELLER_OS_ROADMAP_PHASES_V1[0]
const P2 = SELLER_OS_ROADMAP_PHASES_V1[1]
const P3 = SELLER_OS_ROADMAP_PHASES_V1[2]
const P4 = SELLER_OS_ROADMAP_PHASES_V1[3]
const P5 = SELLER_OS_ROADMAP_PHASES_V1[4]
const P6 = SELLER_OS_ROADMAP_PHASES_V1[5]
const P6B = SELLER_OS_ROADMAP_PHASES_V1[6]
const P7 = SELLER_OS_ROADMAP_PHASES_V1[7]
const P8 = SELLER_OS_ROADMAP_PHASES_V1[8]
const P9 = SELLER_OS_ROADMAP_PHASES_V1[9]
const P10 = SELLER_OS_ROADMAP_PHASES_V1[10]

export const SELLER_OS_CROSS_PHASE_REUSE_MAP_V1 = Object.freeze({
  contractVersion: SELLER_OS_CROSS_PHASE_REUSE_MAP_VERSION,
  roadmap: SELLER_OS_ROADMAP_PHASES_V1,
  entries: Object.freeze([
    entry({ capability: "OFFICIAL_EBAY_ORDER_AUTHORITY",
      responsibility: "Bounded PII-free official eBay Fulfillment order evidence",
      canonicalOwner: "P1-I01_OFFICIAL_ORDERS_READ_V1",
      canonicalImplementation: ["lib/ebay/ebay-official-orders-read-v1.ts"],
      currentConsumers: ["P1-I02", "P1-I03"],
      futureConsumers: [P1, P3, P6, P6B, P8, P9, P10],
      classification: "REUSE_AS_IS", contractVersion: "SELLER_OS_OFFICIAL_ORDERS_READ_V1",
      extensionPolicy: "Add optional bounded metadata only; never substitute Analytics",
      safetyClass: "READ_ONLY_NO_BUYER_PII", sideEffectClass: "OBSERVABILITY_READ",
      deprecationStatus: "ACTIVE", limitations: ["FIXED_RECENT_30_DAY_WINDOW"] }),
    entry({ capability: "SALES_ORDER_LINE_EVENT_IDENTITY",
      responsibility: "One deterministic sale identity per official order line",
      canonicalOwner: "P1-I02_SALES_ORDER_EVENT_FOUNDATION_V1",
      canonicalImplementation: ["lib/ebay/ebay-sales-order-event-foundation-v1.ts",
        "lib/ebay/ebay-sales-order-events-read-v1.ts"],
      currentConsumers: ["P1-I03"], futureConsumers: [P1, P2, P3, P5, P6B, P8, P9, P10],
      classification: "REUSE_AS_IS", contractVersion: "SELLER_OS_SALES_ORDER_EVENTS_READ_V1",
      extensionPolicy: "Certified commercial-v1 event IDs are immutable; add child IDs without rewriting them",
      safetyClass: "DETERMINISTIC_PII_FREE", sideEffectClass: "OBSERVABILITY_READ",
      deprecationStatus: "ACTIVE", limitations: ["EVENT_PROJECTION_NOT_PERSISTED_BY_READ"] }),
    entry({ capability: "CANONICAL_RECENT_SALES_FEED",
      responsibility: "Stable line-grained recent sales operational projection",
      canonicalOwner: "P1-I03_SALES_ORDER_READ_MODEL_RECENT_FEED_V1",
      canonicalImplementation: ["lib/ebay/ebay-sales-order-read-model-v1.ts"],
      currentConsumers: ["P1-I04"], futureConsumers: [P1, P2, P3, P6B, P8, P9, P10],
      classification: "REUSE_AS_IS", contractVersion: "SELLER_OS_RECENT_SALES_FEED_V1",
      extensionPolicy: "Preserve eventId grain and deterministic ordering; add consumers, not alternate feeds",
      safetyClass: "READ_ONLY_NO_BUYER_PII", sideEffectClass: "OBSERVABILITY_READ",
      deprecationStatus: "ACTIVE", limitations: ["DETERMINISTIC_PROJECTION_FROM_LIVE_EVENTS"] }),
    entry({ capability: "CANONICAL_SELLER_ACCOUNT_BINDING",
      responsibility: "Fix all Seller OS reads and actions to the canonical marketplace account",
      canonicalOwner: "SELLER_ACCOUNT_SCOPE_FOUNDATION",
      canonicalImplementation: ["lib/ebay/ebay-seller-account-scope.ts"],
      currentConsumers: ["COMMERCIAL_MONITOR", "CLOUD_READ_RELAY"],
      futureConsumers: [P1, P2, P3, P4, P5, P6, P6B, P7, P8, P9, P10],
      classification: "REUSE_AS_IS", contractVersion: null,
      extensionPolicy: "No caller-controlled account selection; add marketplace adapters behind fixed binding",
      safetyClass: "FIXED_ACCOUNT", sideEffectClass: "NONE",
      deprecationStatus: "ACTIVE", limitations: ["CURRENT_MARKETPLACE_EBAY_US"] }),
    entry({ capability: "CANONICAL_CLOUD_READ_RELAY",
      responsibility: "Authenticated fixed allowlisted cloud reads without copying provider secrets locally",
      canonicalOwner: "TUNNEL_CLOUD_READ_RELAY_FOUNDATION",
      canonicalImplementation: ["lib/ebay/ebay-seller-os-cloud-read-relay-v1.ts"],
      currentConsumers: ["OFFICIAL_ORDERS", "COMMERCIAL_READ_TOOLS"],
      futureConsumers: [P1, P2, P3, P6B, P7, P9], classification: "EXTEND_CANONICAL",
      contractVersion: "SELLER_OS_CLOUD_READ_RELAY_V1",
      extensionPolicy: "Only fixed tool allowlist additions with server-owned auth and bounded responses",
      safetyClass: "SERVER_AUTHENTICATED_READ", sideEffectClass: "OBSERVABILITY_READ",
      deprecationStatus: "ACTIVE", limitations: ["NOT_A_GENERIC_NETWORK_PROXY"] }),
    entry({ capability: "RUNTIME_WORKSPACE_CERTIFICATION",
      responsibility: "Bind workspace, loaded MCP implementation, catalog and live runtime",
      canonicalOwner: "TUNNEL_OBSERVABILITY_FOUNDATION",
      canonicalImplementation: ["lib/ebay/ebay-seller-os-runtime-health-v1.ts",
        "lib/ebay/ebay-seller-os-dev-status-v1.ts",
        "lib/ebay/ebay-seller-os-ci-status-v1.ts"],
      currentConsumers: ["I01", "I02", "I03", "I04", "P1-I01", "P1-I02", "P1-I03"],
      futureConsumers: [P1, P2, P3, P4, P5, P6, P6B, P7, P8, P9, P10],
      classification: "REUSE_AS_IS", contractVersion: "SELLER_OS_RUNTIME_CATALOG_ATTESTATION_V1",
      extensionPolicy: "Every independently certified capability needs bounded live evidence; prefer existing resources",
      safetyClass: "LOCAL_READ_ONLY_ATTESTATION", sideEffectClass: "OBSERVABILITY_READ",
      deprecationStatus: "ACTIVE", limitations: [] }),
    entry({ capability: "FRESHNESS_AND_STALENESS",
      responsibility: "Keep observation time, source update time, evidence age and exact-subject freshness distinct",
      canonicalOwner: "TUNNEL_OBSERVABILITY_FOUNDATION",
      canonicalImplementation: ["lib/ebay/commercial-monitor-readonly-contract.ts",
        "lib/ebay/ebay-seller-os-ci-status-v1.ts",
        "lib/ebay/ebay-seller-os-data-status-v1.ts"],
      currentConsumers: ["COMMERCIAL_MONITOR", "CI_STATUS", "DATA_STATUS"],
      futureConsumers: [P1, P2, P3, P4, P5, P6, P6B, P7, P8, P9, P10],
      classification: "EXTEND_CANONICAL", contractVersion: "SELLER_OS_FRESHNESS_POLICY_V1",
      extensionPolicy: "Domain thresholds may differ, but observedAt, sourceUpdatedAt and subject freshness must not be conflated",
      safetyClass: "BOUNDED_METADATA", sideEffectClass: "NONE",
      deprecationStatus: "ACTIVE", limitations: ["DOMAIN_MAXIMUM_AGE_THRESHOLDS_REMAIN_SPECIALIZED"] }),
    entry({ capability: "DATA_MIGRATION_OBSERVABILITY",
      responsibility: "Fail-closed authoritative migration and schema evidence",
      canonicalOwner: "TUNNEL-OBS-I04_DATA_MIGRATION_STATUS_V1",
      canonicalImplementation: ["lib/ebay/ebay-seller-os-data-status-v1.ts"],
      currentConsumers: ["TUNNEL_CERTIFICATION"], futureConsumers: [P1, P2, P3, P4, P5, P6, P6B, P7, P8, P9, P10],
      classification: "REUSE_AS_IS", contractVersion: "SELLER_OS_DATA_STATUS_V1",
      extensionPolicy: "Never infer schema parity from migration IDs and never mutate to make status green",
      safetyClass: "READ_ONLY_DATA_CONTROL", sideEffectClass: "OBSERVABILITY_READ",
      deprecationStatus: "ACTIVE", limitations: ["GLOBAL_SCHEMA_DRIFT_CURRENTLY_UNPROVEN"] }),
    entry({ capability: "EVIDENCE_AUTHORITY_AND_PROVENANCE",
      responsibility: "Separate official, observed, persisted, derived, inferred and recommended evidence",
      canonicalOwner: "COMMERCIAL_MONITOR_READONLY_FOUNDATION",
      canonicalImplementation: ["lib/ebay/commercial-monitor-readonly-contract.ts",
        "lib/ebay/ebay-official-orders-read-v1.ts"],
      currentConsumers: ["COMMERCIAL_MONITOR", "P1-I01", "P1-I02", "P1-I03"],
      futureConsumers: [P1, P2, P3, P5, P6, P6B, P7, P8, P9, P10],
      classification: "EXTEND_CANONICAL", contractVersion: "SELLER_OS_EVIDENCE_PROVENANCE_POLICY_V1",
      extensionPolicy: "Domain provenance may add fields but must retain authority class, timestamps and limitations",
      safetyClass: "BOUNDED_METADATA", sideEffectClass: "NONE",
      deprecationStatus: "ACTIVE", limitations: ["SPECIALIZED_PROVENANCE_REMAINS_DOMAIN_OWNED"] }),
    entry({ capability: "PII_SECRETS_BOUNDARY",
      responsibility: "Keep secrets and buyer-sensitive data out of Tunnel, logs and audit payloads",
      canonicalOwner: "SELLER_OS_MCP_SECURITY_BOUNDARY",
      canonicalImplementation: ["lib/ebay/ebay-seller-os-mcp-tool-policy-v1.ts",
        "lib/ebay/ebay-official-orders-read-v1.ts"],
      currentConsumers: ["MCP", "CLOUD_READ_RELAY", "OFFICIAL_ORDERS"],
      futureConsumers: [P1, P2, P3, P4, P5, P6, P6B, P7, P8, P9, P10],
      classification: "EXTEND_CANONICAL", contractVersion: "SELLER_OS_SENSITIVE_DATA_POLICY_V1",
      extensionPolicy: "P6B may use purpose-bound PII internally but never surface it through MCP/logs/snapshots",
      safetyClass: "SENSITIVE_DATA_DENY_BY_DEFAULT", sideEffectClass: "NONE",
      deprecationStatus: "ACTIVE", limitations: ["INTERNAL_PURPOSE_BOUND_PII_ADAPTER_NOT_YET_DEFINED"] }),
    entry({ capability: "MCP_BOUNDED_READ_POLICY",
      responsibility: "Fixed account, bounded inputs/results and no arbitrary proxy, SQL, token or path",
      canonicalOwner: "SELLER_OS_MCP_READONLY_FOUNDATION",
      canonicalImplementation: ["lib/ebay/ebay-seller-os-mcp-server-v1.ts",
        "lib/ebay/ebay-seller-os-mcp-tool-policy-v1.ts"],
      currentConsumers: ["SELLER_OS_TUNNEL"], futureConsumers: [P1, P2, P3, P4, P5, P6, P6B, P7, P8, P9, P10],
      classification: "REUSE_AS_IS", contractVersion: "SELLER_OS_MCP_READONLY_V1",
      extensionPolicy: "Extend an existing tool/resource when responsibility is coherent; new tool only for independent certification boundary",
      safetyClass: "READ_ONLY_BOUNDED", sideEffectClass: "OBSERVABILITY_READ",
      deprecationStatus: "ACTIVE", limitations: [] }),
    entry({ capability: "CROSS_DOMAIN_STABLE_IDENTITY_POLICY",
      responsibility: "Deterministic replay identity while preserving each domain's immutable natural grain",
      canonicalOwner: "W0_IDENTITY_IDEMPOTENCY_POLICY",
      canonicalImplementation: ["lib/marketplace/commercial-monitor-domain.ts",
        "lib/ebay/ebay-sales-order-event-foundation-v1.ts"],
      currentConsumers: ["SALES_EVENTS", "COMMERCIAL_ALERTS"],
      futureConsumers: [P1, P2, P3, P4, P5, P6B, P7, P8, P9, P10],
      classification: "EXTEND_CANONICAL", contractVersion: "SELLER_OS_IDENTITY_IDEMPOTENCY_POLICY_V1",
      extensionPolicy: "Keep certified IDs unchanged; new domains declare grain/version and derive deterministic business IDs",
      safetyClass: "DETERMINISTIC_METADATA", sideEffectClass: "NONE",
      deprecationStatus: "ACTIVE", limitations: ["NO_SINGLE_HASH_HELPER_CAN_DEFINE_ALL_DOMAIN_GRAINS"] }),
    entry({ capability: "WORKFLOW_STEP_EXECUTION_CONTRACT",
      responsibility: "Shared step states, attempts, leases and retry-safe side-effect receipts",
      canonicalOwner: "W0_REPLAY_RETRY_RESTART_POLICY",
      canonicalImplementation: ["lib/ebay/ebay-seller-os-workflow-foundation-v1.ts"], currentConsumers: ["P1-I04"],
      futureConsumers: [P1, P2, P4, P5, P6B], classification: "NEW_SHARED_CAPABILITY",
      contractVersion: "SELLER_OS_WORKFLOW_STEP_EXECUTION_V1",
      extensionPolicy: "Implement once at first write-capable consumer; reuse existing domain stores through adapters",
      safetyClass: "WRITE_GATED", sideEffectClass: "DOMAIN_DEFINED",
      deprecationStatus: "ACTIVE",
      limitations: ["CURRENT_RUNTIME_ADAPTER_IS_NON_PERSISTED_DASHBOARD_PROJECTION"] }),
    entry({ capability: "CROSS_DOMAIN_CORRELATION_ENVELOPE",
      responsibility: "Link business fact, event, decision, step, external action and outcome",
      canonicalOwner: "W0_AUDIT_TRAIL_POLICY",
      canonicalImplementation: ["lib/ebay/ebay-seller-os-workflow-foundation-v1.ts"],
      currentConsumers: ["P1-I04"], futureConsumers: [P1, P2, P3, P4, P5, P6B, P8, P9, P10],
      classification: "NEW_SHARED_CAPABILITY", contractVersion: "SELLER_OS_CORRELATION_ENVELOPE_V1",
      extensionPolicy: "Add linkage metadata without replacing domain IDs or building a new event-sourcing platform",
      safetyClass: "METADATA_NO_PII", sideEffectClass: "NONE",
      deprecationStatus: "ACTIVE",
      limitations: ["CORRELATION_ENVELOPE_NOT_DURABLY_PERSISTED"] }),
    entry({ capability: "CATEGORIZED_STATUS_TAXONOMY",
      responsibility: "Prevent source, runtime, validation, workflow and decision status conflation",
      canonicalOwner: "W0_STATUS_POLICY", canonicalImplementation: ["W0_CONTRACT_ONLY"],
      currentConsumers: [], futureConsumers: [P1, P2, P3, P4, P5, P6, P6B, P7, P8, P9, P10],
      classification: "NEW_SHARED_CAPABILITY", contractVersion: "SELLER_OS_STATUS_TAXONOMY_V1",
      extensionPolicy: "Every status field declares category; specialized enums remain valid within category",
      safetyClass: "METADATA", sideEffectClass: "NONE",
      deprecationStatus: "CONTRACT_ONLY_IMPLEMENTATION_DEFERRED", limitations: [] }),
    entry({ capability: "SIDE_EFFECT_CLASSIFICATION",
      responsibility: "Separate internal maintenance writes from external business actions",
      canonicalOwner: "W0_SIDE_EFFECT_POLICY", canonicalImplementation: ["W0_CONTRACT_ONLY"],
      currentConsumers: [], futureConsumers: [P1, P2, P3, P4, P5, P6B, P10],
      classification: "NEW_SHARED_CAPABILITY", contractVersion: "SELLER_OS_SIDE_EFFECT_TAXONOMY_V1",
      extensionPolicy: "Every write-capable contract reports count and authority per side-effect class",
      safetyClass: "WRITE_ACCOUNTING", sideEffectClass: "NONE",
      deprecationStatus: "CONTRACT_ONLY_IMPLEMENTATION_DEFERRED", limitations: [] }),
    entry({ capability: "AUDIT_TRAIL_CHAIN",
      responsibility: "Reconstruct fact to event to decision to delivery/action to outcome",
      canonicalOwner: "COMMERCIAL_EVENT_AUDIT_FOUNDATION",
      canonicalImplementation: ["lib/ebay/ebay-sales-order-readonly-audit-repository-v1.ts",
        "lib/ebay/ebay-commercial-monitor-service.ts"],
      currentConsumers: ["COMMERCIAL_MONITOR", "WHATSAPP_DELIVERY_AUDIT"],
      futureConsumers: [P1, P2, P3, P4, P5, P6B, P8, P9, P10],
      classification: "EXTEND_CANONICAL", contractVersion: "SELLER_OS_AUDIT_TRAIL_POLICY_V1",
      extensionPolicy: "Reuse existing ledgers and add correlation envelope fields; no broad event-sourcing rewrite",
      safetyClass: "PII_FREE_AUDIT_METADATA", sideEffectClass: "INTERNAL_IDEMPOTENT_MAINTENANCE_WRITE",
      deprecationStatus: "ACTIVE", limitations: ["CROSS_DOMAIN_CORRELATION_NOT_YET_PERSISTED"] }),
    entry({ capability: "AUTOMATION_AUTHORITY_MODEL",
      responsibility: "Separate read, recommendation, approval-required and auto-execution authority",
      canonicalOwner: "SELLER_OS_SAFETY_AND_APPROVAL_FOUNDATION",
      canonicalImplementation: ["lib/ebay/commercial-monitor-readonly-contract.ts",
        "lib/ebay/ebay-listing-ai-approval-queue.ts"],
      currentConsumers: ["COMMERCIAL_MONITOR", "LISTING_APPROVAL"],
      futureConsumers: [P1, P2, P3, P4, P5, P6B, P7, P10],
      classification: "EXTEND_CANONICAL", contractVersion: "SELLER_OS_AUTOMATION_AUTHORITY_V1",
      extensionPolicy: "Default READ_ONLY; explicit policy and evidence required for any higher authority",
      safetyClass: "HUMAN_GATED", sideEffectClass: "DOMAIN_DEFINED",
      deprecationStatus: "ACTIVE", limitations: ["NO_GLOBAL_AUTO_EXECUTION_PROMOTION_SERVICE"] }),
    entry({ capability: "HUMAN_REVIEW_GATE",
      responsibility: "Bound uncertainty, reason codes, evidence and approval before high-risk continuation",
      canonicalOwner: "SELLER_OS_HUMAN_REVIEW_FOUNDATION",
      canonicalImplementation: ["lib/ebay/commercial-monitor-readonly-contract.ts",
        "lib/ebay/ebay-commercial-monitor-experiment-v1.ts"],
      currentConsumers: ["REGISTRY", "EXPERIMENTS", "COMMERCIAL_RECOMMENDATIONS"],
      futureConsumers: [P1, P2, P3, P4, P5, P6B, P7, P9, P10],
      classification: "EXTEND_CANONICAL", contractVersion: "SELLER_OS_HUMAN_REVIEW_GATE_V1",
      extensionPolicy: "Domain-specific review reasons are allowed; execution remains blocked until explicit decision",
      safetyClass: "HUMAN_GATED", sideEffectClass: "NONE",
      deprecationStatus: "ACTIVE", limitations: ["MULTIPLE_DOMAIN_UI_QUEUES_REMAIN"] }),
    entry({ capability: "LUNA_SUPPLIER_LINKAGE_IDENTITY",
      responsibility: "Variant-specific human-approved identity from one canonical live eBay Item ID to one Luna product/variant",
      canonicalOwner: "P2-I01_LUNA_SUPPLIER_LINKAGE",
      canonicalImplementation: [
        "lib/ebay/ebay-luna-supplier-linkage-certification-v1.ts",
        "lib/ebay/ebay-luna-supplier-stock-watcher-v1.ts",
      ],
      currentConsumers: ["P2-I01", "COMMERCIAL_MONITOR"],
      futureConsumers: [P2, P3, P6B, P9],
      classification: "EXTEND_CANONICAL",
      contractVersion: "SELLER_OS_LUNA_SUPPLIER_LINKAGE_STATUS_V1",
      extensionPolicy: "Reuse the existing exact Luna approval envelope and W0 human-review gate; historical/manual mappings remain candidates until exact variant approval",
      safetyClass: "HUMAN_GATED_SUPPLIER_IDENTITY",
      sideEffectClass: "OBSERVABILITY_READ",
      deprecationStatus: "ACTIVE",
      limitations: ["LINKAGE_DOES_NOT_CERTIFY_STOCK_OR_AUTHORIZE_MARKETPLACE_ACTIONS"] }),
    entry({ capability: "LUNA_STOCK_OBSERVATION",
      responsibility: "Authenticated supplier variant stock observation and freshness",
      canonicalOwner: "P2-I02_AUTOMATIC_LUNA_STOCK_OBSERVATION",
      canonicalImplementation: ["lib/ebay/ebay-luna-supplier-stock-watcher-v1.ts",
        "lib/ebay/ebay-luna-authenticated-http-watcher-v1.ts",
        "lib/ebay/ebay-luna-stock-observation-v1.ts"],
      currentConsumers: ["COMMERCIAL_MONITOR", "P2-I02"],
      futureConsumers: [P2, P3, P6B, P9],
      classification: "DOMAIN_SPECIFIC",
      contractVersion: "SELLER_OS_LUNA_STOCK_OBSERVATION_V1",
      extensionPolicy: "Reuse shared evidence/freshness/identity policies; keep supplier parsing domain-owned",
      safetyClass: "SUPPLIER_READ", sideEffectClass: "OBSERVABILITY_READ",
      deprecationStatus: "ACTIVE", limitations: [] }),
    entry({ capability: "COMMERCIAL_DECISION_LOOP",
      responsibility: "Classify commercial evidence and recommend bounded actions",
      canonicalOwner: "PHASE_3", canonicalImplementation: ["lib/ebay/ebay-commercial-monitor-intelligence-v1.ts"],
      currentConsumers: ["COMMERCIAL_MONITOR"], futureConsumers: [P3, P4, P5, P9, P10],
      classification: "DOMAIN_SPECIFIC", contractVersion: "COMMERCIAL_MONITOR_BACKEND_V1",
      extensionPolicy: "Consume shared evidence and authority policies; retain commercial scoring locally",
      safetyClass: "RECOMMENDATION", sideEffectClass: "NONE",
      deprecationStatus: "ACTIVE", limitations: [] }),
    entry({ capability: "EXPERIMENT_LIFECYCLE",
      responsibility: "Single-variable experiment state, evidence gate and guardian",
      canonicalOwner: "PHASE_5", canonicalImplementation: ["lib/ebay/ebay-commercial-monitor-experiment-v1.ts"],
      currentConsumers: ["COMMERCIAL_MONITOR"], futureConsumers: [P3, P4, P5, P8, P9],
      classification: "DOMAIN_SPECIFIC", contractVersion: "EBAY_EXPERIMENT_REGISTRY_V1",
      extensionPolicy: "Reuse workflow/correlation policies; do not generalize experiment metrics into workflow states",
      safetyClass: "HUMAN_GATED_EXPERIMENT", sideEffectClass: "INTERNAL_BUSINESS_STATE_WRITE",
      deprecationStatus: "ACTIVE", limitations: [] }),
    entry({ capability: "UNIT_ECONOMICS",
      responsibility: "Marketplace-specific profit, margin and ROI computation",
      canonicalOwner: "PHASE_6", canonicalImplementation: ["lib/ebay/ebay-unit-economics.ts"],
      currentConsumers: ["COMMERCIAL_DECISIONS"], futureConsumers: [P3, P5, P6, P6B, P9, P10],
      classification: "DOMAIN_SPECIFIC", contractVersion: null,
      extensionPolicy: "Inputs use shared provenance; fee/cost formulas remain marketplace-specific and versioned",
      safetyClass: "DERIVED_FINANCIAL_EVIDENCE", sideEffectClass: "NONE",
      deprecationStatus: "ACTIVE", limitations: ["SOME_FEES_ARE_CONSERVATIVE_ESTIMATES"] }),
    entry({ capability: "PROCUREMENT_FULFILLMENT_WORKFLOW",
      responsibility: "Purchase, reconciliation and eBay tracking workflow",
      canonicalOwner: "PHASE_6B", canonicalImplementation: ["lib/marketplace/fulfillment-v1a-domain.ts",
        "lib/marketplace/fulfillment-v1b-domain.ts"],
      currentConsumers: [], futureConsumers: [P6B], classification: "DOMAIN_SPECIFIC",
      contractVersion: "MARKETPLACE_FULFILLMENT_V1", extensionPolicy: "Must adopt W0 workflow, PII, authority and side-effect contracts before activation",
      safetyClass: "PAYMENT_AND_SHIPPING_HIGH_RISK", sideEffectClass: "PAYMENT_TRANSACTION",
      deprecationStatus: "ACTIVE", limitations: ["WRITE_ACTIVATION_REQUIRES_SEPARATE_CERTIFICATION"] }),
    entry({ capability: "EBAY_QUALITY_OPPORTUNITY_RESEARCH",
      responsibility: "Research and rank bounded eBay opportunities and quality signals",
      canonicalOwner: "PHASE_7", canonicalImplementation: ["lib/ebay/ebay-market-opportunity-research-v1.ts"],
      currentConsumers: ["OPPORTUNITY_RADAR"], futureConsumers: [P5, P6, P7, P8, P9, P10],
      classification: "DOMAIN_SPECIFIC", contractVersion: "MARKET_OPPORTUNITY_RESEARCH_V1",
      extensionPolicy: "Consume shared authority/provenance; retain research scoring and source policy locally",
      safetyClass: "RESEARCH_RECOMMENDATION", sideEffectClass: "NONE",
      deprecationStatus: "ACTIVE", limitations: [] }),
    entry({ capability: "CATEGORY_PERFORMANCE_LEARNING",
      responsibility: "Category-specific learning from bounded commercial outcomes",
      canonicalOwner: "PHASE_8", canonicalImplementation: ["lib/ebay/ebay-category-performance-learning.ts"],
      currentConsumers: ["COMMERCIAL_MONITOR"], futureConsumers: [P5, P7, P8, P9, P10],
      classification: "DOMAIN_SPECIFIC", contractVersion: "EBAY_CATEGORY_PERFORMANCE_LEARNING_V1",
      extensionPolicy: "Require correlation/provenance before learning claims; correlation is not causality",
      safetyClass: "DERIVED_LEARNING_EVIDENCE", sideEffectClass: "INTERNAL_IDEMPOTENT_MAINTENANCE_WRITE",
      deprecationStatus: "ACTIVE", limitations: [] }),
    entry({ capability: "PORTFOLIO_INTELLIGENCE",
      responsibility: "Portfolio exceptions, prioritization and cross-listing review",
      canonicalOwner: "PHASE_9", canonicalImplementation: ["lib/ebay/ebay-seller-os-portfolio-intelligence-v1.ts"],
      currentConsumers: ["SELLER_OS_ASSISTANT"], futureConsumers: [P3, P4, P5, P7, P8, P9, P10],
      classification: "DOMAIN_SPECIFIC", contractVersion: "SELLER_OS_PORTFOLIO_INTELLIGENCE_V1",
      extensionPolicy: "Consume shared status/freshness/provenance; retain portfolio ranking locally",
      safetyClass: "RECOMMENDATION", sideEffectClass: "NONE",
      deprecationStatus: "ACTIVE", limitations: [] }),
    entry({ capability: "PRODUCT_CASE_BRIDGE",
      responsibility: "Advance sufficiently proven commercial opportunity into Product Case readiness",
      canonicalOwner: "PHASE_10", canonicalImplementation: ["lib/ebay/ebay-commercial-intelligence-upgrade-v1.ts"],
      currentConsumers: [], futureConsumers: [P10], classification: "DOMAIN_SPECIFIC",
      contractVersion: null, extensionPolicy: "Must consume shared evidence, human review and mutation authority; no direct mutation from read surfaces",
      safetyClass: "HUMAN_GATED_BRIDGE", sideEffectClass: "PRODUCT_CASE_MUTATION",
      deprecationStatus: "ACTIVE", limitations: ["CURRENT_READ_PATH_REPORTS_PRODUCT_CASE_MUTATIONS_ZERO"] }),
    entry({ capability: "LEGACY_ORDER_GRAIN_RECENT_SALES_FEED",
      responsibility: "Legacy persisted recent-sales aggregate grouped by order",
      canonicalOwner: "COMMERCIAL_MONITOR_LEGACY_READ_MODEL",
      canonicalImplementation: ["lib/ebay/ebay-sales-order-read-model-v1.ts#projectRecentSalesFeedV1"],
      currentConsumers: ["COMMERCIAL_MONITOR_DASHBOARD"], futureConsumers: [],
      classification: "DUPLICATE_TO_REMOVE", contractVersion: "RECENT_SALES_FEED_V1",
      extensionPolicy: "Do not add consumers; migrate dashboard to certified line-grained feed under a separate compatibility delta",
      safetyClass: "READ_ONLY", sideEffectClass: "OBSERVABILITY_READ",
      deprecationStatus: "DEPRECATE_AFTER_CONSUMER_MIGRATION",
      limitations: ["ORDER_GRAIN_CONFLICTS_WITH_CERTIFIED_ORDER_LINE_GRAIN"] }),
    entry({ capability: "LEGACY_ORDER_GRAIN_SALE_DETECTED_EVENT",
      responsibility: "Persisted SALE_DETECTED aggregate with one logical event per order",
      canonicalOwner: "COMMERCIAL_MONITOR_LEGACY_EVENT_WRITER",
      canonicalImplementation: ["lib/ebay/ebay-commercial-monitor-service.ts"],
      currentConsumers: ["COMMERCIAL_ALERT_OUTBOX", "LEGACY_AUDIT"], futureConsumers: [],
      classification: "DUPLICATE_TO_REMOVE", contractVersion: "SALE_ATTRIBUTION_V1",
      extensionPolicy: "Do not rewrite history; migrate future consumers to line event plus explicit order aggregate relationship",
      safetyClass: "INTERNAL_WRITE", sideEffectClass: "INTERNAL_IDEMPOTENT_MAINTENANCE_WRITE",
      deprecationStatus: "DEPRECATE_AFTER_CONSUMER_MIGRATION",
      limitations: ["ORDER_GRAIN_DIFFERS_FROM_CERTIFIED_P1_I02_EVENT_GRAIN"] }),
  ]),
})

export const SELLER_OS_CROSS_PHASE_REUSE_POLICY_V1 = Object.freeze({
  contractVersion: SELLER_OS_CROSS_PHASE_REUSE_POLICY_VERSION,
  creationGate: Object.freeze([
    "EQUIVALENT_CAPABILITY_SEARCHED",
    "REUSE_AS_IS_EVALUATED",
    "EXTEND_CANONICAL_EVALUATED",
    "NEW_SHARED_CAPABILITY_JUSTIFIED",
    "DOMAIN_SPECIFIC_BOUNDARY_JUSTIFIED",
  ]),
  identityAndIdempotency: Object.freeze({
    contractVersion: "SELLER_OS_IDENTITY_IDEMPOTENCY_POLICY_V1",
    certifiedSalesOrderEventIdentityFrozen: true,
    certifiedGrain:
      "CANONICAL_ACCOUNT_MARKETPLACE_ORDER_ID_LINE_ITEM_ID_EVENT_TYPE_VERSION",
    businessIdentityInputs: Object.freeze([
      "CANONICAL_ACCOUNT", "MARKETPLACE", "IMMUTABLE_DOMAIN_GRAIN",
      "EVENT_OR_OPERATION_TYPE", "VERSION",
    ]),
    forbiddenBusinessIdentityInputs: Object.freeze([
      "PROCESSING_TIMESTAMP", "RANDOM_UUID", "RETRY_COUNT", "WORKER_ID",
    ]),
    attemptAndLeaseIdsMayBeRandom: true,
    replayInvariant: "SAME_BUSINESS_FACT_REPLAYED_N_TIMES_SAME_LOGICAL_IDENTITY",
  }),
  evidenceAuthority: Object.freeze({
    contractVersion: "SELLER_OS_EVIDENCE_AUTHORITY_MODEL_V1",
    classes: Object.freeze([
      "OFFICIAL_EXTERNAL_FACT", "DIRECT_OBSERVATION", "DURABLY_PERSISTED_FACT",
      "DERIVED_FACT", "INFERENCE", "RECOMMENDATION", "UNPROVEN", "UNAVAILABLE",
    ]),
    rules: Object.freeze([
      "ANALYTICS_QUANTITY_SOLD_IS_NOT_OFFICIAL_ORDERS",
      "NO_EVIDENCE_DOES_NOT_PROVE_ZERO", "UNKNOWN_IS_NOT_ZERO",
      "INFERENCE_IS_NOT_OFFICIAL_FACT", "CORRELATION_IS_NOT_CAUSALITY",
      "ZERO_REQUIRES_SUCCESSFUL_COMPLETE_AUTHORITATIVE_READ",
    ]),
  }),
  provenance: Object.freeze({
    contractVersion: "SELLER_OS_EVIDENCE_PROVENANCE_POLICY_V1",
    requiredFields: Object.freeze([
      "authorityClass", "source", "sourceContractVersion", "operation",
      "accountBinding", "observedAt", "sourceUpdatedAt", "evidenceReferences",
      "evidenceCompleteness", "limitations",
    ]),
    specializedDomainFieldsAllowed: true,
  }),
  statusTaxonomy: Object.freeze({
    contractVersion: "SELLER_OS_STATUS_TAXONOMY_V1",
    source: Object.freeze(["AVAILABLE", "PARTIAL", "UNAVAILABLE", "UNPROVEN"]),
    overallData: Object.freeze(["HEALTHY", "DEGRADED", "BLOCKED", "UNAVAILABLE", "UNPROVEN"]),
    runtime: Object.freeze(["HEALTHY", "DEGRADED", "FAILED", "UNAVAILABLE"]),
    validation: Object.freeze(["PASS", "FAIL", "PARTIAL", "STALE", "UNAVAILABLE"]),
    workflow: Object.freeze(["NOT_STARTED", "IN_PROGRESS", "SUCCEEDED",
      "RETRYABLE_FAILURE", "TERMINAL_FAILURE", "BLOCKED", "SKIPPED", "NOT_APPLICABLE"]),
    decision: Object.freeze(["READY", "BLOCKED", "HUMAN_REVIEW", "REJECTED", "UNPROVEN"]),
    rule: "STATUS_CATEGORY_MUST_BE_DECLARED_AND_CROSS_CATEGORY_SUCCESS_MUST_NOT_BE_INFERRED",
  }),
  sensitiveData: Object.freeze({
    contractVersion: "SELLER_OS_SENSITIVE_DATA_POLICY_V1",
    tunnelForbidden: Object.freeze(["ACCESS_TOKEN", "REFRESH_TOKEN", "CLIENT_SECRET",
      "PASSWORD", "COOKIE", "AUTHORIZATION_HEADER", "CARD_NUMBER", "CVV",
      "RAW_ENVIRONMENT_VALUE", "RAW_UPSTREAM_PAYLOAD"]),
    buyerPiiTunnelForbidden: Object.freeze(["BUYER_NAME", "BUYER_USERNAME",
      "EMAIL", "PHONE", "SHIPPING_ADDRESS", "BILLING_ADDRESS", "PAYMENT_DATA"]),
    internalBuyerPiiRule:
      "AUTHORIZED_BACKEND_PURPOSE_BOUND_MINIMUM_NECESSARY_NO_LOG_NO_MCP_NO_SNAPSHOT",
    defaultPolicy: "DENY_BY_DEFAULT",
  }),
  certificationObservability: Object.freeze({
    chain: Object.freeze(["WORKSPACE", "RUNTIME_LOADED_IMPLEMENTATION",
      "MCP_CATALOG", "TUNNEL", "LIVE_EVIDENCE"]),
    newToolRule:
      "CREATE_ONLY_FOR_DISTINCT_INDEPENDENT_CERTIFICATION_OR_SECURITY_BOUNDARY",
    existingSurfaceRule:
      "PREFER_EXISTING_TOOL_EXTENSION_OR_ALLOWLISTED_SEARCH_FETCH_RESOURCE",
  }),
  retryReplayRestart: Object.freeze({
    contractVersion: "SELLER_OS_WORKFLOW_STEP_EXECUTION_V1",
    states: Object.freeze(["NOT_STARTED", "IN_PROGRESS", "SUCCEEDED",
      "RETRYABLE_FAILURE", "TERMINAL_FAILURE", "BLOCKED", "SKIPPED", "NOT_APPLICABLE"]),
    invariants: Object.freeze([
      "BUSINESS_FACT_IDENTITY_SEPARATE_FROM_ATTEMPT_ID",
      "LEASE_TOKEN_SEPARATE_FROM_IDEMPOTENCY_KEY",
      "EACH_SIDE_EFFECT_HAS_CHILD_DEDUPLICATION_KEY",
      "SUCCESS_RECEIPT_PREVENTS_DUPLICATE_SIDE_EFFECT_AFTER_RESTART",
      "ONE_STEP_FAILURE_DOES_NOT_REPLAY_SUCCEEDED_SIBLING_STEPS",
    ]),
  }),
  auditTrail: Object.freeze({
    contractVersion: "SELLER_OS_AUDIT_TRAIL_POLICY_V1",
    chain: Object.freeze(["BUSINESS_FACT", "DETECTION", "EVENT", "DECISION",
      "NOTIFICATION_OR_EXTERNAL_ACTION", "OUTCOME"]),
    correlationEnvelope: Object.freeze(["businessFactId", "eventId", "correlationId",
      "causationId", "stepExecutionId", "sideEffectReceiptId"]),
    eventSourcingPlatformRequired: false,
  }),
  automationAuthority: Object.freeze({
    contractVersion: "SELLER_OS_AUTOMATION_AUTHORITY_V1",
    levels: Object.freeze(["READ_ONLY", "RECOMMENDATION",
      "HUMAN_APPROVAL_REQUIRED", "AUTO_EXECUTION_ALLOWED"]),
    defaultLevel: "READ_ONLY",
    policyOwner: "SELLER_OS_SAFETY_AND_APPROVAL_FOUNDATION",
    paymentAndProcurementDefault: "HUMAN_APPROVAL_REQUIRED",
  }),
  sideEffects: Object.freeze({
    contractVersion: "SELLER_OS_SIDE_EFFECT_TAXONOMY_V1",
    classes: Object.freeze(["OBSERVABILITY_READ", "INTERNAL_IDEMPOTENT_MAINTENANCE_WRITE",
      "INTERNAL_BUSINESS_STATE_WRITE", "MARKETPLACE_WRITE", "INVENTORY_WRITE",
      "WHATSAPP_SEND", "BUYER_MESSAGE_SEND", "PRODUCT_CASE_MUTATION", "LUNA_MUTATION",
      "PAYMENT_TRANSACTION", "SHIPPING_FULFILLMENT_WRITE"]),
    rule: "REPORT_INTERNAL_DATABASE_WRITES_SEPARATELY_FROM_EXTERNAL_BUSINESS_ACTIONS",
  }),
  boundedRead: Object.freeze({
    contractVersion: "SELLER_OS_BOUNDED_READ_POLICY_V1",
    required: Object.freeze(["FIXED_CANONICAL_ACCOUNT", "FIXED_SOURCE_ALLOWLIST",
      "BOUNDED_TIME_WINDOW", "BOUNDED_RESULTS", "BOUNDED_PAGES", "TRUNCATION_EXPLICIT"]),
    forbidden: Object.freeze(["ARBITRARY_URL", "ARBITRARY_SQL", "CALLER_TOKEN",
      "CALLER_ACCOUNT", "CALLER_REPOSITORY", "CALLER_FILE_PATH", "CALLER_SHELL_COMMAND"]),
    exceptionPolicy: "EXPLICIT_DOMAIN_CONTRACT_WITH_STRICT_VALIDATION_AND_SEPARATE_REVIEW",
  }),
  freshness: Object.freeze({
    contractVersion: "SELLER_OS_FRESHNESS_POLICY_V1",
    fields: Object.freeze(["observedAt", "sourceUpdatedAt", "maximumAgeSeconds",
      "ageSeconds", "freshnessStatus", "subjectFingerprint"]),
    statuses: Object.freeze(["FRESH", "STALE", "UNKNOWN", "NOT_APPLICABLE"]),
    rules: Object.freeze(["OBSERVED_AT_IS_NOT_SOURCE_UPDATED_AT",
      "STALE_EVIDENCE_CANNOT_SILENTLY_BECOME_CURRENT",
      "PERSISTED_CERTIFICATION_EVIDENCE_REQUIRES_EXACT_SUBJECT_FINGERPRINT"]),
  }),
  humanReview: Object.freeze({
    contractVersion: "SELLER_OS_HUMAN_REVIEW_GATE_V1",
    requiredFields: Object.freeze(["required", "reasonCodes", "evidenceReferences",
      "requestedAt", "decisionStatus", "authorityRequired"]),
    decisionStates: Object.freeze(["PENDING", "APPROVED", "REJECTED", "EXPIRED", "CANCELLED"]),
    invariant: "NO_GATED_EXTERNAL_ACTION_BEFORE_EXPLICIT_VALID_APPROVAL",
  }),
})

export const SELLER_OS_CROSS_PHASE_DUPLICATION_AUDIT_V1 = Object.freeze([
  Object.freeze({ auditedConcern: "READ_MODEL_IDENTITY",
    implementationA: "projectRecentSalesFeedV1_ORDER_GRAIN",
    implementationB: "buildSellerOsRecentSalesFeedV1_ORDER_LINE_GRAIN",
    sameResponsibility: "YES", risk: "HIGH_SEMANTIC_GRAIN_DIVERGENCE",
    classification: "DUPLICATE_TO_REMOVE" as const,
    recommendedAction: "DEPRECATE_LEGACY_AFTER_DASHBOARD_COMPATIBILITY_MIGRATION" }),
  Object.freeze({ auditedConcern: "EVENT_IDENTITY",
    implementationA: "PERSISTED_SALE_DETECTED_ORDER_GRAIN",
    implementationB: "CERTIFIED_SALES_ORDER_EVENT_ORDER_LINE_GRAIN",
    sameResponsibility: "YES", risk: "HIGH_DUPLICATE_SALE_OR_ALERT_ON_REPLAY",
    classification: "DUPLICATE_TO_REMOVE" as const,
    recommendedAction: "PRESERVE_HISTORY_AND_MIGRATE_NEW_CONSUMERS_TO_LINE_EVENT_IDENTITY" }),
  Object.freeze({ auditedConcern: "OAUTH_AUTH_RESOLUTION",
    implementationA: "LOCAL_EBAY_OAUTH_ADAPTER",
    implementationB: "CANONICAL_CLOUD_READ_RELAY_OAUTH",
    sameResponsibility: "NO", risk: "MEDIUM_TOPOLOGY_WIRING_DRIFT",
    classification: "EXTEND_CANONICAL" as const,
    recommendedAction: "KEEP_DEPLOYMENT_ADAPTERS_BEHIND_ONE_CANONICAL_ACCOUNT_AUTH_POLICY" }),
  Object.freeze({ auditedConcern: "IDEMPOTENCY",
    implementationA: "COMMERCIAL_STABLE_KEYS",
    implementationB: "WHATSAPP_EXPERIMENT_FULFILLMENT_IDEMPOTENCY_KEYS",
    sameResponsibility: "NO", risk: "MEDIUM_INCONSISTENT_GRAIN_DOCUMENTATION",
    classification: "EXTEND_CANONICAL" as const,
    recommendedAction: "REQUIRE_W0_GRAIN_VERSION_DECLARATION_WITHOUT_REWRITING_IDS" }),
  Object.freeze({ auditedConcern: "STATUS_ENUMS",
    implementationA: "SOURCE_STATUS_ENUMS",
    implementationB: "RUNTIME_VALIDATION_WORKFLOW_STATUS_ENUMS",
    sameResponsibility: "NO", risk: "MEDIUM_CROSS_CATEGORY_STATUS_CONFLATION",
    classification: "NEW_SHARED_CAPABILITY" as const,
    recommendedAction: "ADOPT_CATEGORIZED_STATUS_TAXONOMY_IN_NEW_CONTRACTS" }),
  Object.freeze({ auditedConcern: "RETRY_LOGIC",
    implementationA: "OUTBOX_AND_COMMERCIAL_EVENT_RETRIES",
    implementationB: "FULFILLMENT_AND_IMAGE_LEASE_RETRIES",
    sameResponsibility: "NO", risk: "HIGH_DUPLICATE_SIDE_EFFECT_IF_STEPS_SHARE_KEYS",
    classification: "NEW_SHARED_CAPABILITY" as const,
    recommendedAction: "ADOPT_SHARED_STEP_STATE_AND_CHILD_SIDE_EFFECT_RECEIPT_CONTRACT" }),
  Object.freeze({ auditedConcern: "PROVENANCE",
    implementationA: "COMMERCIAL_MONITOR_OBSERVATION_PROVENANCE",
    implementationB: "OFFICIAL_ORDER_AND_SALES_EVENT_PROVENANCE",
    sameResponsibility: "NO", risk: "MEDIUM_AUTHORITY_OR_TIMESTAMP_CONFLATION",
    classification: "EXTEND_CANONICAL" as const,
    recommendedAction: "REUSE_BASE_PROVENANCE_FIELDS_AND_KEEP_DOMAIN_EVIDENCE_REFERENCES" }),
  Object.freeze({ auditedConcern: "AUDIT_LOGGING",
    implementationA: "COMMERCIAL_EVENT_AND_DELIVERY_AUDIT",
    implementationB: "FULFILLMENT_WORKFLOW_AUDIT",
    sameResponsibility: "NO", risk: "HIGH_MISSING_CROSS_DOMAIN_CAUSATION_LINK",
    classification: "EXTEND_CANONICAL" as const,
    recommendedAction: "ADD_CORRELATION_ENVELOPE_WITHOUT_MERGING_DOMAIN_LEDGERS" }),
  Object.freeze({ auditedConcern: "APPROVAL_HUMAN_GATE",
    implementationA: "LISTING_AI_APPROVAL_QUEUE",
    implementationB: "EXPERIMENT_AND_FULFILLMENT_HUMAN_GATES",
    sameResponsibility: "NO", risk: "HIGH_APPROVAL_REUSED_OUTSIDE_BOUND_CONTEXT",
    classification: "EXTEND_CANONICAL" as const,
    recommendedAction: "REUSE_AUTHORITY_LEVELS_AND_BIND_APPROVAL_TO_EXACT_PAYLOAD_CONTEXT" }),
  Object.freeze({ auditedConcern: "SAFETY_RESPONSE",
    implementationA: "MCP_REGISTRATION_POLICY_GUARD",
    implementationB: "DOMAIN_RESPONSE_SAFETY_COUNTERS",
    sameResponsibility: "NO", risk: "MEDIUM_STATIC_POLICY_AND_OBSERVED_COUNTER_CONFLATION",
    classification: "EXTEND_CANONICAL" as const,
    recommendedAction: "KEEP_BOTH_AND_REQUIRE_STATIC_AUTHORITY_PLUS_OBSERVED_SIDE_EFFECT_COUNTS" }),
  Object.freeze({ auditedConcern: "MCP_BOUNDS",
    implementationA: "MCP_INPUT_SCHEMA_BOUNDS",
    implementationB: "DOMAIN_WINDOW_PAGE_AND_RESULT_BOUNDS",
    sameResponsibility: "NO", risk: "HIGH_UNBOUNDED_DOMAIN_FETCH_BEHIND_BOUNDED_INPUT",
    classification: "EXTEND_CANONICAL" as const,
    recommendedAction: "REQUIRE_TRANSPORT_AND_DOMAIN_BOUNDS_SIMULTANEOUSLY" }),
  Object.freeze({ auditedConcern: "SOURCE_EVIDENCE_SEMANTICS",
    implementationA: "COMMERCIAL_OBSERVATION_AVAILABILITY",
    implementationB: "ORDERS_DATA_AND_MIGRATION_SOURCE_STATUSES",
    sameResponsibility: "NO", risk: "HIGH_UNKNOWN_OR_UNAVAILABLE_REPORTED_AS_ZERO",
    classification: "EXTEND_CANONICAL" as const,
    recommendedAction: "REUSE_EVIDENCE_AUTHORITY_RULES_WITH_CATEGORY_SPECIFIC_STATUS_ENUMS" }),
])

export const SELLER_OS_CROSS_PHASE_ARCHITECTURE_INVENTORY_V1 = Object.freeze({
  contractVersion: SELLER_OS_CROSS_PHASE_SHARED_FOUNDATION_VERSION,
  layers: Object.freeze([
    Object.freeze({ layer: "AUTHORITATIVE_SOURCES", owners: Object.freeze([
      "EBAY_SELL_FULFILLMENT", "EBAY_SELL_ANALYTICS", "LUNA", "SUPABASE_LEDGER"]),
    }),
    Object.freeze({ layer: "NORMALIZATION_AND_EVIDENCE", owners: Object.freeze([
      "COMMERCIAL_MONITOR_READONLY_CONTRACT", "OFFICIAL_ORDERS", "SALES_ORDER_EVENTS"]),
    }),
    Object.freeze({ layer: "READ_MODELS_AND_INTELLIGENCE", owners: Object.freeze([
      "RECENT_SALES_FEED", "COMMERCIAL_MONITOR", "PORTFOLIO_INTELLIGENCE"]),
    }),
    Object.freeze({ layer: "EXECUTION_AND_DELIVERY", owners: Object.freeze([
      "COMMERCIAL_OUTBOX", "FULFILLMENT_WORKFLOWS", "APPROVAL_GATES"]),
    }),
    Object.freeze({ layer: "OBSERVABILITY_AND_CERTIFICATION", owners: Object.freeze([
      "RUNTIME_HEALTH", "DEV_STATUS", "CI_STATUS", "DATA_STATUS", "MCP_SEARCH_FETCH"]),
    }),
  ]),
})

const SAFETY = Object.freeze({
  readOnly: true as const,
  buyerPiiIncluded: false as const,
  credentialsIncluded: false as const,
  environmentValuesIncluded: false as const,
  fileContentsIncluded: false as const,
  rawUpstreamPayloadIncluded: false as const,
  arbitraryUrlAllowed: false as const,
  callerControlledAccountAllowed: false as const,
  callerControlledTokenAllowed: false as const,
  databaseWrites: 0 as const,
  marketplaceWrites: 0 as const,
  inventoryWrites: 0 as const,
  productCaseMutations: 0 as const,
  lunaLinkMutations: 0 as const,
  lunaMutations: 0 as const,
  whatsappSends: 0 as const,
  buyerMessageSends: 0 as const,
  paymentTransactions: 0 as const,
})

export function getSellerOsCrossPhaseFoundationV1() {
  return Object.freeze({
    contractVersion: SELLER_OS_CROSS_PHASE_SHARED_FOUNDATION_VERSION,
    architectureInventory: SELLER_OS_CROSS_PHASE_ARCHITECTURE_INVENTORY_V1,
    reuseMap: SELLER_OS_CROSS_PHASE_REUSE_MAP_V1,
    reusePolicy: SELLER_OS_CROSS_PHASE_REUSE_POLICY_V1,
    duplicationAudit: SELLER_OS_CROSS_PHASE_DUPLICATION_AUDIT_V1,
    safety: SAFETY,
  })
}
