import test from 'node:test'
import assert from 'node:assert/strict'
import {currentPreparationActivationEvidenceV1 as evidence,currentPreparationActivationReadbackV1 as readback} from './ebay-current-preparation-activation-v1.ts'
import {keywordWireDigestV1 as digest} from '../seller-os/keyword-intelligence-handoff-v1.ts'
import {currentPackagePreviewRevisionV1 as revisionView} from '../seller-os/publication-package-preparation-v1.ts'
const now=new Date('2026-09-11T13:00:00Z')
function fixture(){
 const snapshot={generation:'generation',binding:{PRODUCT_ID:'product',VARIANT_ID:'variant',SKU:'supplier'},content:{title:'current'}},preview={sku:'sku',inventoryItemPayload:{product:{title:'current'},availability:{shipToLocationAvailability:{quantity:1}},condition:'NEW'},offerPayload:{categoryId:'261987',pricingSummary:{price:{value:'17.77',currency:'USD'}}}}
 const r={version:'SELLER_OS_PACKAGE_PREVIEW_REVISION_V1',publicationId:'publication',packageId:'package',accountKey:'account',productId:'product',variantId:'variant',sku:'supplier',revisionKey:'revision',priorDraftExecutionId:'historical',snapshot,packageGeneration:snapshot.generation,packageHash:digest(snapshot),preview,previewHash:digest(preview)}
 const b={publicationId:'publication',packageId:'package',accountKey:'account',offerId:'offer',sku:'sku',packageHash:r.packageHash,packageGeneration:r.packageGeneration,previewHash:r.previewHash}
 const inv={safe:true,httpStatus:200},offer={safe:true,httpStatus:200,offerId:'offer',sku:'sku',status:'UNPUBLISHED',listingPresent:false,payloadMatches:true}
 const receipt={version:'CURRENT_UNPUBLISHED_PREPARATION_V1',key:digest(b),binding:b,state:'READBACK_CONFIRMED',publicationAuthorized:false,observedAt:now.toISOString(),result:{pass:true,inventoryReadback:inv,offerReadback:offer}}
 const p={id:'publication',actor_user_id:'owner',listing_package_id:'package',marketplace_account_key:'account',account_fingerprint:'fp',sku:'sku',offer_id:'offer',phase:'preview_ready',publish_attempt_count:0,publication_idempotency_key:null,claim_token:null,listing_id:null,sanitized_result:{publicationPreparationV1:{current:r},currentUnpublishedPreparationV1:receipt}}
 const f={publicationId:p.id,packageId:r.packageId,packageHash:r.packageHash,packageGeneration:r.packageGeneration,previewHash:r.previewHash,observedAt:now.toISOString(),currentOfferReadback:offer,currentInventoryReadback:inv,officialAccountPreflight:{status:'READY',identity:{status:'BOUND',accountFingerprint:'fp'}},currentPolicySelectionExact:true,officialCategoryPreflight:{safe:true},imageAuthority:{pass:true},currentPreparationReceiptBound:true,preflightErrors:[],warnings:[]}
 return {p,r,f}
}
function activated(){
 const {p,r,f}=fixture(),proof=evidence(p,f,now),payload={inventoryItemPayload:r.preview.inventoryItemPayload,offerPayload:r.preview.offerPayload,economics:{historicalStateInherited:false}}
 Object.assign(p,{draft_execution_id:'new-execution',draft_approval_id:'new-approval',preview:r.preview,preview_hash:r.previewHash})
 p.sanitized_result.publicationPreparationV1.activation={version:'CURRENT_PREPARATION_ACTIVATION_V1',scope:'PREPARE_UNPUBLISHED_ONLY',publicationId:p.id,draftExecutionId:p.draft_execution_id,draftApprovalId:p.draft_approval_id,previewHash:p.preview_hash,activatedAt:now.toISOString(),receiptBindingKey:proof.key,publicationAuthorized:false,historicalExecutionReused:false}
 const e={id:p.draft_execution_id,approval_id:p.draft_approval_id,phase:'completed',offer_id:p.offer_id,sku:p.sku,actor_user_id:p.actor_user_id,listing_package_id:p.listing_package_id,account_fingerprint:p.account_fingerprint,request_hash:'hash',sanitized_result:{currentPreparationActivationV1:proof}}
 const a={id:p.draft_approval_id,actor_user_id:p.actor_user_id,listing_package_id:p.listing_package_id,account_fingerprint:p.account_fingerprint,status:'consumed',approval_phrase_version:'CURRENT_PREPARATION_RECONCILIATION_V1',payload_hash:'hash',approved_payload:payload}
 return {p,r,e,a}
}
test('CURRENT official acceptance activates only preparation, without inheriting historical economics',()=>{const {p,f}=fixture(),before=structuredClone(p),v=evidence(p,f,now);assert.equal(v.publicationAuthorized,false);assert.equal(v.economicsInherited,false);assert.deepEqual(p,before);const x=activated();assert.equal(readback(x.p,x.e,x.a),true)})
for(const field of ['publicationId','packageId','packageHash','packageGeneration','previewHash'])test('reject stale/cross binding '+field,()=>{const {p,f}=fixture();f[field]='other';assert.throws(()=>evidence(p,f,now),/EVIDENCE_INVALID/)})
test('unpublished, exact content, QA and official readback are required even with old receipt',()=>{for(const mutate of [f=>f.currentOfferReadback.safe=false,f=>f.currentOfferReadback.status='PUBLISHED',f=>f.currentOfferReadback.listingPresent=true,f=>f.currentOfferReadback.payloadMatches=false,f=>f.imageAuthority.pass=false,f=>f.currentInventoryReadback.safe=false,f=>f.officialAccountPreflight.identity.accountFingerprint='other',f=>f.preflightErrors=['error'],f=>f.warnings=['unclassified']]){const {p,f}=fixture();mutate(f);assert.throws(()=>evidence(p,f,now))}})
test('fresh evidence required, expired/future observation never activates',()=>{for(const dt of [-120001,1]){const {p,f}=fixture();f.observedAt=new Date(now.getTime()+dt).toISOString();assert.throws(()=>evidence(p,f,now))}})
test('in-flight or consumed publication key cannot be reconciled as unused',()=>{for(const patch of [{publish_attempt_count:1},{publication_idempotency_key:'publish-key'},{claim_token:'claim'},{phase:'publish_in_flight'},{listing_id:'live'}]){const {p,f}=fixture();Object.assign(p,patch);assert.throws(()=>evidence(p,f,now))}})
test('durable readback rejects historical execution, economics, payload, and wrong approval',()=>{for(const mutate of [x=>x.e.id='historical',x=>x.e.approval_id='historical',x=>x.a.approval_phrase_version='OWNER_HISTORIC',x=>x.a.approved_payload.economics.historicalStateInherited=true,x=>x.e.account_fingerprint='other',x=>x.p.preview_hash='old',x=>x.e.sanitized_result.currentPreparationActivationV1.binding.previewGeneration='old']){const x=activated();mutate(x);assert.equal(readback(x.p,x.e,x.a),false)}})
test('activation binds full current Offer and condition, not just title/quantity',()=>{const x=activated(),g={PACKAGE_CONSISTENT:true,PACKAGE_HASH:x.r.packageHash,snapshot:x.r.snapshot};assert.equal(revisionView(x.r,g,x.p,x.p.sanitized_result.publicationPreparationV1.activation).valid,true);for(const mutate of [p=>p.preview.offerPayload.categoryId='other',p=>p.preview.inventoryItemPayload.condition='USED']){const p=structuredClone(x.p);mutate(p);assert.equal(revisionView(x.r,g,p,x.p.sanitized_result.publicationPreparationV1.activation).valid,false)}})
