export const PRODUCTION_EBAY_PRO_CLEANUP_EXACT_COUNT_VERIFICATION_VERSION =
  "PRODUCTION_EBAY_PRO_CLEANUP_EXACT_COUNT_VERIFICATION_V1"

const exactCountVerifiedTables = [
  {
    tableName:
      "ebay_active_listing_risk_events",
    exactRows:
      0,
  },
  {
    tableName:
      "ebay_active_listings",
    exactRows:
      0,
  },
  {
    tableName:
      "ebay_candidate_decisions",
    exactRows:
      0,
  },
  {
    tableName:
      "ebay_candidate_scores",
    exactRows:
      0,
  },
  {
    tableName:
      "ebay_candidate_validations",
    exactRows:
      0,
  },
  {
    tableName:
      "ebay_compliance_checks",
    exactRows:
      0,
  },
  {
    tableName:
      "ebay_listing_drafts",
    exactRows:
      0,
  },
  {
    tableName:
      "ebay_pipeline_audit_log",
    exactRows:
      0,
  },
  {
    tableName:
      "ebay_price_intelligence_snapshots",
    exactRows:
      0,
  },
  {
    tableName:
      "ebay_product_candidates",
    exactRows:
      0,
  },
  {
    tableName:
      "ebay_profit_scenarios",
    exactRows:
      0,
  },
  {
    tableName:
      "market_radar_events",
    exactRows:
      0,
  },
  {
    tableName:
      "market_radar_products",
    exactRows:
      0,
  },
  {
    tableName:
      "market_radar_scores",
    exactRows:
      0,
  },
  {
    tableName:
      "market_radar_snapshots",
    exactRows:
      0,
  },
  {
    tableName:
      "market_radar_sources",
    exactRows:
      0,
  },
] as const

export function getExactCountVerifiedTables() {
  return exactCountVerifiedTables.map((table) => ({ ...table }))
}

export function getProductionCleanupFinalStatus() {
  return {
    exactCountVerificationDocumented:
      true,
    exactCountVerificationExecutedManuallyBeforeThisLoop:
      true,
    allTargetTablesExactRowsZero:
      true,
    productionCleanupFinalVerified:
      true,
    productionPhysicallyCleanOfEbayProMarketRadarData:
      true,
    stagingTouched:
      false,
    schemaDropped:
      false,
    viewsDropped:
      false,
    backupCommittedToRepo:
      false,
    liveDbQueriedInThisLoop:
      false,
    sqlExecutedInThisLoop:
      false,
  }
}

export function getProductionCleanupExactCountVerification() {
  return {
    exactCountVerificationVersion:
      PRODUCTION_EBAY_PRO_CLEANUP_EXACT_COUNT_VERIFICATION_VERSION,
    caseId:
      "PRODUCTION-EBAY-PRO-CLEANUP-EXACT-COUNT-001",
    status:
      "PRODUCTION_EBAY_PRO_CLEANUP_EXACT_COUNT_VERIFIED",
    mode:
      "POST_EXECUTION_EXACT_COUNT_RECORD_STATIC_ONLY",
    backup:
      {
        manualBackupCreated:
          true,
        backupSize:
          "60 MB",
        backupCommittedToRepo:
          false,
        dumpFileCommitted:
          false,
        connectionStringCommitted:
          false,
        secretsCommitted:
          false,
      },
    verification:
      getProductionCleanupFinalStatus(),
    targetTables:
      getExactCountVerifiedTables(),
    notTouched:
      {
        staging:
          true,
        schema:
          true,
        tables:
          true,
        views:
          true,
        products:
          true,
        subscribers:
          true,
        notificationLogs:
          true,
        whatsappCore:
          true,
        communityTables:
          true,
        vm:
          true,
      },
    safetyFlags:
      {
        postExecutionRecordOnly:
          true,
        liveDbQueriedInThisLoop:
          false,
        sqlExecutedInThisLoop:
          false,
        supabaseWriteUsedInThisLoop:
          false,
        cleanupExecutedBeforeThisLoopManually:
          true,
        exactCountExecutedBeforeThisLoopManually:
          true,
        exactCountVerificationDocumented:
          true,
        physicalDbCleanupApplied:
          true,
        allTargetTablesExactRowsZero:
          true,
        backupConfirmed:
          true,
        backupCommittedToRepo:
          false,
        dumpFileCommitted:
          false,
        connectionStringCommitted:
          false,
        secretsCommitted:
          false,
        stagingTouched:
          false,
        schemaDropped:
          false,
        viewsDropped:
          false,
        dropTableUsed:
          false,
        dropViewUsed:
          false,
        cascadeUsed:
          false,
        vmConnected:
          false,
        ebayApiUsed:
          false,
        oauthUsed:
          false,
        openAiUsed:
          false,
        imageGenerationUsed:
          false,
        whatsappRealSendUsed:
          false,
      },
  }
}
