-- Close direct client access on the append-only Visual Strategy V3 tables
-- created by already-applied migrations. This changes no rows, ownership,
-- RLS policy, provider state, Storage object or eBay object.

revoke all on table public.ebay_reference_guided_replacement_canary_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_replacement_canary_events from public;
revoke all on table public.ebay_reference_guided_human_review_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_human_review_events from public;
revoke all on table public.ebay_reference_guided_deterministic_previews from anon, authenticated;
revoke all on table public.ebay_reference_guided_deterministic_previews from public;
revoke all on table public.ebay_reference_guided_asset_contract_slots from anon, authenticated;
revoke all on table public.ebay_reference_guided_asset_contract_slots from public;
revoke all on table public.ebay_reference_guided_primary_main_previews from anon, authenticated;
revoke all on table public.ebay_reference_guided_primary_main_previews from public;
revoke all on table public.ebay_reference_guided_asset_review_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_asset_review_events from public;
revoke all on table public.ebay_reference_guided_deterministic_asset_variants from anon, authenticated;
revoke all on table public.ebay_reference_guided_deterministic_asset_variants from public;
revoke all on table public.ebay_reference_guided_final_asset_selection_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_final_asset_selection_events from public;
revoke all on table public.ebay_reference_guided_final_batch_plans from anon, authenticated;
revoke all on table public.ebay_reference_guided_final_batch_plans from public;
revoke all on table public.ebay_reference_guided_final_batch_plan_positions from anon, authenticated;
revoke all on table public.ebay_reference_guided_final_batch_plan_positions from public;
revoke all on table public.ebay_reference_guided_batch_plan_successors_v2 from anon, authenticated;
revoke all on table public.ebay_reference_guided_batch_plan_successors_v2 from public;
revoke all on table public.ebay_reference_guided_batch_plan_successor_positions_v2 from anon, authenticated;
revoke all on table public.ebay_reference_guided_batch_plan_successor_positions_v2 from public;
revoke all on table public.ebay_reference_guided_phase_a_position_2_assets from anon, authenticated;
revoke all on table public.ebay_reference_guided_phase_a_position_2_assets from public;
revoke all on table public.ebay_reference_guided_successor_provider_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_successor_provider_events from public;
revoke all on table public.ebay_reference_guided_position_5_human_verdict_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_position_5_human_verdict_events from public;
revoke all on table public.ebay_reference_guided_position_3_human_verdict_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_position_3_human_verdict_events from public;
revoke all on table public.ebay_reference_guided_position_contract_amendments from anon, authenticated;
revoke all on table public.ebay_reference_guided_position_contract_amendments from public;
revoke all on table public.ebay_reference_guided_position_4_human_verdict_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_position_4_human_verdict_events from public;
revoke all on table public.ebay_reference_guided_position_4_correction_amendments from anon, authenticated;
revoke all on table public.ebay_reference_guided_position_4_correction_amendments from public;
revoke all on table public.ebay_reference_guided_position_6_contract_amendments from anon, authenticated;
revoke all on table public.ebay_reference_guided_position_6_contract_amendments from public;
revoke all on table public.ebay_reference_guided_position_6_human_verdict_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_position_6_human_verdict_events from public;
revoke all on table public.ebay_reference_guided_position_4_fidelity_amendments from anon, authenticated;
revoke all on table public.ebay_reference_guided_position_4_fidelity_amendments from public;
revoke all on table public.ebay_reference_guided_position_6_correction_amendments from anon, authenticated;
revoke all on table public.ebay_reference_guided_position_6_correction_amendments from public;
revoke all on table public.ebay_reference_guided_extraordinary_replacement_plans from anon, authenticated;
revoke all on table public.ebay_reference_guided_extraordinary_replacement_plans from public;
revoke all on table public.ebay_reference_guided_extraordinary_replacement_positions from anon, authenticated;
revoke all on table public.ebay_reference_guided_extraordinary_replacement_positions from public;
revoke all on table public.ebay_reference_guided_extraordinary_authorization_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_extraordinary_authorization_events from public;
revoke all on table public.ebay_reference_guided_extraordinary_provider_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_extraordinary_provider_events from public;
revoke all on table public.ebay_reference_guided_position_4_extraordinary_human_verdict_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_position_4_extraordinary_human_verdict_events from public;
revoke all on table public.ebay_reference_guided_position_6_extraordinary_human_verdict_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_position_6_extraordinary_human_verdict_events from public;
revoke all on table public.ebay_reference_guided_final_listing_review_previews from anon, authenticated;
revoke all on table public.ebay_reference_guided_final_listing_review_previews from public;
revoke all on table public.ebay_reference_guided_final_listing_reconciliation_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_final_listing_reconciliation_events from public;
revoke all on table public.ebay_reference_guided_final_listing_gate_source_events from anon, authenticated;
revoke all on table public.ebay_reference_guided_final_listing_gate_source_events from public;
revoke all on table public.ebay_v3_publication_image_transports from anon, authenticated;
revoke all on table public.ebay_v3_publication_image_transports from public;
revoke all on table public.ebay_v3_unpublished_offer_authorization_previews from anon, authenticated;
revoke all on table public.ebay_v3_unpublished_offer_authorization_previews from public;
revoke all on table public.ebay_v3_unpublished_offer_authorization_invalidations from anon, authenticated;
revoke all on table public.ebay_v3_unpublished_offer_authorization_invalidations from public;
revoke all on table public.ebay_v3_listing_package_reconciliations from anon, authenticated;
revoke all on table public.ebay_v3_listing_package_reconciliations from public;
revoke all on table public.ebay_draft_only_approval_reconciliation_events from anon, authenticated;
revoke all on table public.ebay_draft_only_approval_reconciliation_events from public;

notify pgrst, 'reload schema';
