begin;

create table if not exists public.ebay_openai_use_case_configs (
  use_case_id text primary key,
  version text not null,
  enabled boolean not null default false,
  mode text not null default 'SHADOW'
    check (mode in ('SHADOW', 'HUMAN_ASSISTED', 'POLICY_ADVISORY')),
  kill_switch_engaged boolean not null default true,
  model_tier text not null
    check (model_tier in ('ECONOMY', 'BALANCED', 'ADVANCED', 'IMAGE', 'EMBEDDING')),
  model_id text,
  prompt_version text not null,
  schema_version text not null,
  daily_budget_micros bigint not null default 0
    check (daily_budget_micros >= 0),
  monthly_budget_micros bigint not null default 0
    check (monthly_budget_micros >= 0),
  per_product_budget_micros bigint not null default 0
    check (per_product_budget_micros >= 0),
  per_use_case_daily_budget_micros bigint not null default 0
    check (per_use_case_daily_budget_micros >= 0),
  per_invocation_budget_micros bigint not null default 0
    check (per_invocation_budget_micros >= 0),
  maximum_output_tokens integer not null check (maximum_output_tokens > 0),
  timeout_ms integer not null check (timeout_ms between 1000 and 300000),
  maximum_retries integer not null default 0 check (maximum_retries between 0 and 2),
  circuit_failure_threshold integer not null default 3
    check (circuit_failure_threshold between 1 and 20),
  allow_single_advanced_escalation boolean not null default false,
  retention_policy text not null default 'HASHES_AND_SANITIZED_RESULT_ONLY',
  eval_suite text not null,
  updated_by text not null default 'MIGRATION',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.ebay_openai_invocations (
  id uuid primary key default gen_random_uuid(),
  marketplace_account_key text not null,
  marketplace text not null,
  use_case_id text not null references public.ebay_openai_use_case_configs(use_case_id),
  product_ref_hash text not null check (product_ref_hash ~ '^[a-f0-9]{64}$'),
  dossier_hash text not null check (dossier_hash ~ '^[a-f0-9]{64}$'),
  idempotency_key text not null check (idempotency_key ~ '^[a-f0-9]{64}$'),
  mode text not null default 'SHADOW' check (mode = 'SHADOW'),
  status text not null check (status in (
    'LEASED', 'SHADOW_COMPLETED', 'FAILED', 'WAITING_OPENAI_RETRY',
    'DEDUPE_HIT', 'BUDGET_BLOCKED', 'CIRCUIT_OPEN', 'CANCELLED'
  )),
  model_tier text not null,
  model_id text not null,
  prompt_version text not null,
  schema_version text not null,
  input_manifest jsonb not null default '{}'::jsonb,
  input_hash text not null check (input_hash ~ '^[a-f0-9]{64}$'),
  output_hash text check (output_hash is null or output_hash ~ '^[a-f0-9]{64}$'),
  sanitized_result jsonb,
  raw_prompt_persisted boolean not null default false
    check (raw_prompt_persisted = false),
  raw_response_persisted boolean not null default false
    check (raw_response_persisted = false),
  estimated_cost_micros bigint not null default 0
    check (estimated_cost_micros >= 0),
  actual_cost_micros bigint not null default 0
    check (actual_cost_micros >= 0),
  input_tokens bigint not null default 0 check (input_tokens >= 0),
  cached_input_tokens bigint not null default 0 check (cached_input_tokens >= 0),
  cache_write_tokens bigint not null default 0 check (cache_write_tokens >= 0),
  output_tokens bigint not null default 0 check (output_tokens >= 0),
  provider_request_id_hash text,
  error_code text check (
    error_code is null or error_code ~ '^[A-Z0-9_]{1,120}$'
  ),
  lease_owner text,
  lease_expires_at timestamptz,
  attempts integer not null default 1 check (attempts between 0 and 3),
  created_at timestamptz not null default now(),
  completed_at timestamptz,
  updated_at timestamptz not null default now()
);

create unique index if not exists ebay_openai_invocations_idempotency_uidx
  on public.ebay_openai_invocations (
    marketplace_account_key,
    marketplace,
    use_case_id,
    idempotency_key
  );

create index if not exists ebay_openai_invocations_status_idx
  on public.ebay_openai_invocations (status, lease_expires_at, created_at);

create table if not exists public.ebay_openai_budget_usage (
  id bigint generated by default as identity primary key,
  marketplace_account_key text not null,
  marketplace text not null,
  use_case_id text not null references public.ebay_openai_use_case_configs(use_case_id),
  product_ref_hash text,
  period_kind text not null check (period_kind in ('DAY', 'MONTH')),
  period_start date not null,
  reserved_cost_micros bigint not null default 0 check (reserved_cost_micros >= 0),
  actual_cost_micros bigint not null default 0 check (actual_cost_micros >= 0),
  invocation_count bigint not null default 0 check (invocation_count >= 0),
  updated_at timestamptz not null default now()
);

create unique index if not exists ebay_openai_budget_usage_scope_uidx
  on public.ebay_openai_budget_usage (
    marketplace_account_key,
    marketplace,
    use_case_id,
    coalesce(product_ref_hash, ''),
    period_kind,
    period_start
  );

create table if not exists public.ebay_openai_circuit_breakers (
  marketplace_account_key text not null,
  marketplace text not null,
  use_case_id text not null references public.ebay_openai_use_case_configs(use_case_id),
  status text not null default 'CLOSED'
    check (status in ('CLOSED', 'OPEN', 'HALF_OPEN')),
  consecutive_global_failures integer not null default 0
    check (consecutive_global_failures >= 0),
  opened_at timestamptz,
  retry_after timestamptz,
  last_error_code text,
  updated_at timestamptz not null default now(),
  primary key (marketplace_account_key, marketplace, use_case_id)
);

create table if not exists public.ebay_openai_shadow_evaluations (
  id uuid primary key default gen_random_uuid(),
  invocation_id uuid not null references public.ebay_openai_invocations(id),
  dataset_version text not null,
  ground_truth_hash text not null check (ground_truth_hash ~ '^[a-f0-9]{64}$'),
  schema_pass boolean not null,
  evidence_reference_pass boolean not null,
  unsupported_claim_count integer not null default 0
    check (unsupported_claim_count >= 0),
  invented_attribute_count integer not null default 0
    check (invented_attribute_count >= 0),
  action_match boolean,
  utility_score numeric(5,2),
  latency_ms integer check (latency_ms is null or latency_ms >= 0),
  classification text not null check (classification in (
    'REJECTED_NO_VALUE',
    'NEEDS_PROMPT_IMPROVEMENT',
    'HUMAN_ASSISTED_ONLY',
    'SAFE_ADVISORY',
    'SAFE_FOR_POLICY_AUTOMATION'
  )),
  evaluator_version text not null,
  created_at timestamptz not null default now(),
  unique (invocation_id, dataset_version, evaluator_version)
);

insert into public.ebay_openai_use_case_configs (
  use_case_id, version, enabled, mode, kill_switch_engaged, model_tier,
  model_id, prompt_version, schema_version, daily_budget_micros,
  monthly_budget_micros, per_product_budget_micros,
  per_use_case_daily_budget_micros, per_invocation_budget_micros,
  maximum_output_tokens, timeout_ms, maximum_retries,
  allow_single_advanced_escalation, eval_suite
)
values
  ('DOSSIER_DISTILLATION','OPENAI_INTELLIGENCE_V1',false,'SHADOW',true,'ECONOMY',null,'DOSSIER_DISTILLATION_PROMPT_V1','OPENAI_INTELLIGENCE_OUTPUT_V1',0,0,0,0,0,1800,25000,1,false,'DOSSIER_DISTILLATION_EVAL_V1'),
  ('COMPARABLE_CLASSIFICATION','OPENAI_INTELLIGENCE_V1',false,'SHADOW',true,'ECONOMY',null,'COMPARABLE_CLASSIFICATION_PROMPT_V1','OPENAI_INTELLIGENCE_OUTPUT_V1',0,0,0,0,0,1800,25000,1,false,'COMPARABLE_CLASSIFICATION_EVAL_V1'),
  ('LISTING_GENERATION','OPENAI_INTELLIGENCE_V1',false,'SHADOW',true,'BALANCED',null,'LISTING_GENERATION_PROMPT_V1','OPENAI_INTELLIGENCE_OUTPUT_V1',0,0,0,0,0,6000,25000,1,false,'LISTING_GENERATION_EVAL_V1'),
  ('LISTING_REVIEW','OPENAI_INTELLIGENCE_V1',false,'SHADOW',true,'BALANCED',null,'LISTING_REVIEW_PROMPT_V1','OPENAI_INTELLIGENCE_OUTPUT_V1',0,0,0,0,0,1800,25000,1,false,'LISTING_REVIEW_EVAL_V1'),
  ('PERFORMANCE_DIAGNOSIS','OPENAI_INTELLIGENCE_V1',false,'SHADOW',true,'BALANCED',null,'PERFORMANCE_DIAGNOSIS_PROMPT_V1','OPENAI_INTELLIGENCE_OUTPUT_V1',0,0,0,0,0,1800,25000,1,false,'PERFORMANCE_DIAGNOSIS_EVAL_V1'),
  ('EXPERIMENT_ANALYSIS','OPENAI_INTELLIGENCE_V1',false,'SHADOW',true,'BALANCED',null,'EXPERIMENT_ANALYSIS_PROMPT_V1','OPENAI_INTELLIGENCE_OUTPUT_V1',0,0,0,0,0,1800,25000,1,false,'EXPERIMENT_ANALYSIS_EVAL_V1'),
  ('QUARANTINE_TRIAGE','OPENAI_INTELLIGENCE_V1',false,'SHADOW',true,'ECONOMY',null,'QUARANTINE_TRIAGE_PROMPT_V1','OPENAI_INTELLIGENCE_OUTPUT_V1',0,0,0,0,0,1800,25000,1,false,'QUARANTINE_TRIAGE_EVAL_V1'),
  ('DAILY_EXECUTIVE_SUMMARY','OPENAI_INTELLIGENCE_V1',false,'SHADOW',true,'ECONOMY',null,'DAILY_EXECUTIVE_SUMMARY_PROMPT_V1','OPENAI_INTELLIGENCE_OUTPUT_V1',0,0,0,0,0,1800,25000,1,false,'DAILY_EXECUTIVE_SUMMARY_EVAL_V1'),
  ('IMAGE_GENERATION','OPENAI_INTELLIGENCE_V1',false,'SHADOW',true,'IMAGE',null,'IMAGE_GENERATION_PROMPT_V1','OPENAI_INTELLIGENCE_OUTPUT_V1',0,0,0,0,0,1,230000,0,false,'IMAGE_GENERATION_EVAL_V1'),
  ('SEMANTIC_EMBEDDING','OPENAI_INTELLIGENCE_V1',false,'SHADOW',true,'EMBEDDING',null,'SEMANTIC_EMBEDDING_PROMPT_V1','OPENAI_INTELLIGENCE_OUTPUT_V1',0,0,0,0,0,1,25000,1,false,'SEMANTIC_EMBEDDING_EVAL_V1')
on conflict (use_case_id) do nothing;

create or replace function public.reserve_ebay_openai_shadow_invocation_v1(
  p_marketplace_account_key text,
  p_marketplace text,
  p_use_case_id text,
  p_product_ref_hash text,
  p_dossier_hash text,
  p_idempotency_key text,
  p_model_id text,
  p_input_hash text,
  p_input_manifest jsonb,
  p_estimated_cost_micros bigint,
  p_lease_owner text,
  p_lease_seconds integer default 90
)
returns jsonb
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  v_config public.ebay_openai_use_case_configs%rowtype;
  v_existing public.ebay_openai_invocations%rowtype;
  v_day_spend bigint;
  v_month_spend bigint;
  v_product_spend bigint;
  v_use_case_spend bigint;
  v_id uuid;
begin
  select * into v_config
  from public.ebay_openai_use_case_configs
  where use_case_id = p_use_case_id
  for update;

  if not found then
    raise exception 'OPENAI_INTELLIGENCE_USE_CASE_UNKNOWN';
  end if;
  if not v_config.enabled or v_config.kill_switch_engaged or v_config.mode <> 'SHADOW' then
    raise exception 'OPENAI_INTELLIGENCE_SHADOW_DISABLED';
  end if;
  if p_estimated_cost_micros < 0
    or p_estimated_cost_micros > v_config.per_invocation_budget_micros then
    raise exception 'OPENAI_INTELLIGENCE_BUDGET_BLOCKED';
  end if;

  select * into v_existing
  from public.ebay_openai_invocations
  where marketplace_account_key = p_marketplace_account_key
    and marketplace = p_marketplace
    and use_case_id = p_use_case_id
    and idempotency_key = p_idempotency_key;
  if found then
    return jsonb_build_object(
      'invocationId', v_existing.id,
      'dedupeHit', true,
      'status', v_existing.status
    );
  end if;

  select coalesce(sum(estimated_cost_micros), 0) into v_day_spend
  from public.ebay_openai_invocations
  where marketplace_account_key = p_marketplace_account_key
    and marketplace = p_marketplace
    and created_at >= date_trunc('day', now());
  select coalesce(sum(estimated_cost_micros), 0) into v_month_spend
  from public.ebay_openai_invocations
  where marketplace_account_key = p_marketplace_account_key
    and marketplace = p_marketplace
    and created_at >= date_trunc('month', now());
  select coalesce(sum(estimated_cost_micros), 0) into v_product_spend
  from public.ebay_openai_invocations
  where marketplace_account_key = p_marketplace_account_key
    and marketplace = p_marketplace
    and product_ref_hash = p_product_ref_hash
    and created_at >= date_trunc('day', now());
  select coalesce(sum(estimated_cost_micros), 0) into v_use_case_spend
  from public.ebay_openai_invocations
  where marketplace_account_key = p_marketplace_account_key
    and marketplace = p_marketplace
    and use_case_id = p_use_case_id
    and created_at >= date_trunc('day', now());

  if v_day_spend + p_estimated_cost_micros > v_config.daily_budget_micros
    or v_month_spend + p_estimated_cost_micros > v_config.monthly_budget_micros
    or v_product_spend + p_estimated_cost_micros > v_config.per_product_budget_micros
    or v_use_case_spend + p_estimated_cost_micros >
      v_config.per_use_case_daily_budget_micros then
    raise exception 'OPENAI_INTELLIGENCE_BUDGET_BLOCKED';
  end if;

  insert into public.ebay_openai_invocations (
    marketplace_account_key, marketplace, use_case_id, product_ref_hash,
    dossier_hash, idempotency_key, mode, status, model_tier, model_id,
    prompt_version, schema_version, input_manifest, input_hash,
    estimated_cost_micros, lease_owner, lease_expires_at
  )
  values (
    p_marketplace_account_key, p_marketplace, p_use_case_id,
    p_product_ref_hash, p_dossier_hash, p_idempotency_key, 'SHADOW',
    'LEASED', v_config.model_tier, p_model_id, v_config.prompt_version,
    v_config.schema_version, p_input_manifest, p_input_hash,
    p_estimated_cost_micros, p_lease_owner,
    now() + make_interval(secs => greatest(30, least(p_lease_seconds, 300)))
  )
  returning id into v_id;

  return jsonb_build_object(
    'invocationId', v_id,
    'dedupeHit', false,
    'status', 'LEASED'
  );
end;
$$;

create or replace function public.complete_ebay_openai_shadow_invocation_v1(
  p_invocation_id uuid,
  p_status text,
  p_output_hash text,
  p_sanitized_result jsonb,
  p_actual_cost_micros bigint,
  p_input_tokens bigint,
  p_cached_input_tokens bigint,
  p_cache_write_tokens bigint,
  p_output_tokens bigint,
  p_provider_request_id_hash text,
  p_error_code text
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if p_status not in ('SHADOW_COMPLETED', 'FAILED', 'WAITING_OPENAI_RETRY') then
    raise exception 'OPENAI_INTELLIGENCE_COMPLETION_STATUS_INVALID';
  end if;
  update public.ebay_openai_invocations
  set status = p_status,
      output_hash = p_output_hash,
      sanitized_result = p_sanitized_result,
      actual_cost_micros = greatest(0, p_actual_cost_micros),
      input_tokens = greatest(0, p_input_tokens),
      cached_input_tokens = greatest(0, p_cached_input_tokens),
      cache_write_tokens = greatest(0, p_cache_write_tokens),
      output_tokens = greatest(0, p_output_tokens),
      provider_request_id_hash = p_provider_request_id_hash,
      error_code = p_error_code,
      lease_owner = null,
      lease_expires_at = null,
      completed_at = now(),
      updated_at = now()
  where id = p_invocation_id
    and status = 'LEASED'
    and mode = 'SHADOW';
  return found;
end;
$$;

create or replace view public.ebay_openai_intelligence_metrics_v1
with (security_invoker = true)
as
select
  marketplace_account_key,
  marketplace,
  created_at::date as metric_date,
  count(*)::bigint as invocation_count,
  count(*) filter (where status = 'SHADOW_COMPLETED')::bigint as completed_count,
  count(*) filter (
    where status = 'SHADOW_COMPLETED' and output_hash is not null
  )::bigint as schema_pass_count,
  count(*) filter (
    where status = 'SHADOW_COMPLETED'
      and jsonb_typeof(sanitized_result -> 'evidenceUsed') = 'array'
  )::bigint as evidence_pass_count,
  count(*) filter (where status = 'DEDUPE_HIT')::bigint as dedupe_hit_count,
  count(*) filter (where status = 'CIRCUIT_OPEN')::bigint as circuit_open_count,
  sum(estimated_cost_micros)::bigint as estimated_cost_micros,
  sum(actual_cost_micros)::bigint as actual_cost_micros,
  sum(input_tokens)::bigint as input_tokens,
  sum(cached_input_tokens)::bigint as cached_input_tokens,
  sum(cache_write_tokens)::bigint as cache_write_tokens,
  sum(output_tokens)::bigint as output_tokens
from public.ebay_openai_invocations
group by marketplace_account_key, marketplace, created_at::date;

alter table public.ebay_openai_use_case_configs enable row level security;
alter table public.ebay_openai_use_case_configs force row level security;
alter table public.ebay_openai_invocations enable row level security;
alter table public.ebay_openai_invocations force row level security;
alter table public.ebay_openai_budget_usage enable row level security;
alter table public.ebay_openai_budget_usage force row level security;
alter table public.ebay_openai_circuit_breakers enable row level security;
alter table public.ebay_openai_circuit_breakers force row level security;
alter table public.ebay_openai_shadow_evaluations enable row level security;
alter table public.ebay_openai_shadow_evaluations force row level security;

revoke all on table public.ebay_openai_use_case_configs from anon, authenticated;
revoke all on table public.ebay_openai_invocations from anon, authenticated;
revoke all on table public.ebay_openai_budget_usage from anon, authenticated;
revoke all on table public.ebay_openai_circuit_breakers from anon, authenticated;
revoke all on table public.ebay_openai_shadow_evaluations from anon, authenticated;
revoke all on public.ebay_openai_intelligence_metrics_v1 from anon, authenticated;
revoke all on function public.reserve_ebay_openai_shadow_invocation_v1(
  text, text, text, text, text, text, text, text, jsonb, bigint, text, integer
) from public, anon, authenticated;
revoke all on function public.complete_ebay_openai_shadow_invocation_v1(
  uuid, text, text, jsonb, bigint, bigint, bigint, bigint, bigint, text, text
) from public, anon, authenticated;

grant select, insert, update on public.ebay_openai_use_case_configs to service_role;
grant select, insert, update on public.ebay_openai_invocations to service_role;
grant select, insert, update on public.ebay_openai_budget_usage to service_role;
grant select, insert, update on public.ebay_openai_circuit_breakers to service_role;
grant select, insert, update on public.ebay_openai_shadow_evaluations to service_role;
grant select on public.ebay_openai_intelligence_metrics_v1 to service_role;
grant execute on function public.reserve_ebay_openai_shadow_invocation_v1(
  text, text, text, text, text, text, text, text, jsonb, bigint, text, integer
) to service_role;
grant execute on function public.complete_ebay_openai_shadow_invocation_v1(
  uuid, text, text, jsonb, bigint, bigint, bigint, bigint, bigint, text, text
) to service_role;

commit;
