-- TEO keeps an auditable memory of owner-executed listing improvements.
-- The application remains read-only toward eBay: the owner changes eBay
-- manually, then TEO confirms the change through the official read connector.

alter table public.ebay_listing_experiments_v1
  add column workflow_kind text not null default 'LEGACY',
  add column owner_execution_status text not null default 'NOT_APPLICABLE',
  add column owner_confirmed_at timestamptz null,
  add column owner_confirmed_by uuid null,
  add column owner_confirmation_note text null,
  add column readback_status text not null default 'NOT_APPLICABLE',
  add column readback_attempted_at timestamptz null,
  add column readback_verified_at timestamptz null,
  add column baseline_listing_snapshot jsonb null,
  add column readback_listing_snapshot jsonb null,
  add column attribution_status text not null default 'UNASSESSED',
  add column result_evaluated_at timestamptz null,
  add constraint ebay_listing_experiments_workflow_kind_check check (
    workflow_kind in ('LEGACY', 'TEO_OWNER_MANUAL')
  ),
  add constraint ebay_listing_experiments_owner_status_check check (
    owner_execution_status in (
      'NOT_APPLICABLE',
      'AWAITING_OWNER',
      'CONFIRMED_BY_OWNER'
    )
  ),
  add constraint ebay_listing_experiments_readback_status_check check (
    readback_status in (
      'NOT_APPLICABLE',
      'AWAITING_OWNER',
      'PENDING_READBACK',
      'VERIFIED_ON_EBAY',
      'READBACK_FAILED'
    )
  ),
  add constraint ebay_listing_experiments_attribution_status_check check (
    attribution_status in (
      'UNASSESSED',
      'CLEAN_SINGLE_VARIABLE',
      'CONTAMINATED_MULTIPLE_VARIABLES'
    )
  ),
  add constraint ebay_listing_experiments_owner_note_check check (
    owner_confirmation_note is null or (
      char_length(owner_confirmation_note) between 1 and 500
      and owner_confirmation_note !~ '[[:cntrl:]]'
    )
  ),
  add constraint ebay_listing_experiments_snapshot_shape_check check (
    (baseline_listing_snapshot is null or
      jsonb_typeof(baseline_listing_snapshot) = 'object')
    and (readback_listing_snapshot is null or
      jsonb_typeof(readback_listing_snapshot) = 'object')
  ),
  add constraint ebay_listing_experiments_teo_manual_check check (
    workflow_kind <> 'TEO_OWNER_MANUAL' or (
      variable_changed in (
        'TITLE', 'PRICE', 'CATEGORY_ID', 'CONDITION_ID', 'SHIPPING_PRICE'
      )
      and owner_execution_status in (
        'AWAITING_OWNER', 'CONFIRMED_BY_OWNER'
      )
      and readback_status in (
        'AWAITING_OWNER', 'PENDING_READBACK',
        'VERIFIED_ON_EBAY', 'READBACK_FAILED'
      )
      and baseline_listing_snapshot is not null
    )
  ),
  add constraint ebay_listing_experiments_owner_confirmation_check check (
    (
      owner_execution_status = 'CONFIRMED_BY_OWNER'
      and owner_confirmed_at is not null
    ) or (
      owner_execution_status <> 'CONFIRMED_BY_OWNER'
      and owner_confirmed_at is null
      and owner_confirmed_by is null
    )
  ),
  add constraint ebay_listing_experiments_readback_verified_check check (
    (
      readback_status = 'VERIFIED_ON_EBAY'
      and readback_verified_at is not null
      and readback_listing_snapshot is not null
      and attribution_status in (
        'CLEAN_SINGLE_VARIABLE',
        'CONTAMINATED_MULTIPLE_VARIABLES'
      )
    ) or (
      readback_status <> 'VERIFIED_ON_EBAY'
      and readback_verified_at is null
    )
  );

create index ebay_listing_experiments_teo_daily_queue_idx
  on public.ebay_listing_experiments_v1 (
    account_key,
    owner_execution_status,
    readback_status,
    updated_at desc
  )
  where workflow_kind = 'TEO_OWNER_MANUAL'
    and lifecycle_status in (
      'READY', 'RUNNING', 'WAITING_FOR_EVIDENCE', 'READY_TO_EVALUATE'
    );

create table public.ebay_listing_experiment_events_v1 (
  event_id bigint generated by default as identity primary key,
  experiment_id text not null references
    public.ebay_listing_experiments_v1(experiment_id) on delete restrict,
  account_key text not null,
  ebay_item_id text not null,
  event_type text not null,
  actor_role text not null,
  actor_user_id uuid null,
  occurred_at timestamptz not null,
  evidence jsonb not null default '{}'::jsonb,
  event_fingerprint text not null,
  created_at timestamptz not null default now(),
  constraint ebay_listing_experiment_events_item_check check (
    ebay_item_id ~ '^[0-9]{9,20}$'
  ),
  constraint ebay_listing_experiment_events_type_check check (
    event_type in (
      'RECOMMENDED',
      'OWNER_CONFIRMED',
      'READBACK_PENDING',
      'READBACK_VERIFIED',
      'READBACK_CONTAMINATED',
      'READBACK_FAILED',
      'RESULT_EVALUATED',
      'CANCELLED'
    )
  ),
  constraint ebay_listing_experiment_events_actor_check check (
    actor_role in ('TEO', 'OWNER', 'SYSTEM')
  ),
  constraint ebay_listing_experiment_events_evidence_check check (
    jsonb_typeof(evidence) = 'object'
  ),
  constraint ebay_listing_experiment_events_fingerprint_check check (
    event_fingerprint ~ '^[a-f0-9]{64}$'
  ),
  constraint ebay_listing_experiment_events_fingerprint_unique
    unique (event_fingerprint)
);

create index ebay_listing_experiment_events_timeline_idx
  on public.ebay_listing_experiment_events_v1 (
    experiment_id, occurred_at desc, event_id desc
  );

alter table public.ebay_listing_experiment_events_v1 enable row level security;

revoke all on table public.ebay_listing_experiment_events_v1
  from public, anon, authenticated;
revoke all on sequence
  public.ebay_listing_experiment_events_v1_event_id_seq
  from public, anon, authenticated;
grant select, insert on table public.ebay_listing_experiment_events_v1
  to service_role;
grant usage, select on sequence
  public.ebay_listing_experiment_events_v1_event_id_seq
  to service_role;

comment on column public.ebay_listing_experiments_v1.workflow_kind is
  'TEO_OWNER_MANUAL means TEO recommends and reads; only OWNER_ADMIN executes the listing edit directly in eBay.';
comment on column public.ebay_listing_experiments_v1.readback_status is
  'CONFIRMED_BY_OWNER is never equivalent to VERIFIED_ON_EBAY; verification requires an official readback.';
comment on column public.ebay_listing_experiments_v1.attribution_status is
  'Multiple observed variable changes contaminate the experiment and prevent an attributable positive result.';
comment on table public.ebay_listing_experiment_events_v1 is
  'Append-only operational memory for TEO owner-manual listing experiments. It stores sanitized evidence and never authorizes an eBay write.';

notify pgrst, 'reload schema';
