import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {fastProductTruthV1,projectFastListingV1,fastReferenceDifferencesV1,validateFastCorrectionV1} from './fast-listing-v1.ts'
import {goldenDigest as digest} from '../ebay/commercial-golden-path-domain-v1.ts'
import {LUNA_FIELD_TRUTH_RECEIPT_FIELDS_V1} from './luna-trace-product-truth-gate-v1.ts'
import {buildGoldenOwnerProductTruthEvidenceV1} from '../ebay/commercial-golden-path-owner-product-truth-v1.ts'

// Synthetic observations exercise gates only; no fixtures enter real ledgers.
const now=new Date('2026-10-04T01:00:00Z'), observed=now.toISOString(), expiry=new Date(+now+3600000).toISOString()
const owner='10000000-0000-4000-8000-000000000001'
function fixture(){
 const values={LUNA_PRODUCT_ID:'fixture-product',LUNA_VARIANT_ID:'fixture-variant',SUPPLIER_SKU:'FIXTURE-ONLY',TITLE:'Fixture Pet Comb',BRAND:'Fixture Brand',MODEL:'Fixture Model',CONDITION:'NEW',QUANTITY_OR_SET_COUNT:1,SUPPLIER_COST:4,SUPPLIER_AVAILABILITY:'AVAILABLE',SUPPLIER_STOCK:10}
 const fields=LUNA_FIELD_TRUTH_RECEIPT_FIELDS_V1.map(FIELD=>({FIELD,VALUE:values[FIELD]??null,SEMANTIC_CLASS:FIELD in values?'FACT':'MISSING',EVIDENCE_STATUS:FIELD in values?'PROVEN':'MISSING',CONTRADICTION:false,EVIDENCE_ID:digest(FIELD),OBSERVED_AT:observed,FRESH_UNTIL:expiry,SOURCE_EVIDENCE:FIELD in values?[{EVIDENCE_ID:digest(FIELD)}]:[]}))
 const source={product_id:values.LUNA_PRODUCT_ID,variant_id:values.LUNA_VARIANT_ID,sku:values.SUPPLIER_SKU,title:values.TITLE,price:4,availability:true,observed_at:observed,source_fingerprint:digest('synthetic'),field_truth_v1:{contractVersion:'LUNA_FIELD_PRODUCT_TRUTH_V1',fields}}
 const corrections=[validateFastCorrectionV1({field:'CONDITION',value:'NEW',actorId:owner,opportunityId:'fixture-case',sourceFingerprint:source.source_fingerprint,previous:null,now})]
 const truth=fastProductTruthV1(source,corrections,now),binding={truthDigest:truth.evidenceDigest,sourceFingerprint:source.source_fingerprint,observedAt:observed,freshUntil:expiry}
 const sold={evidenceId:'synthetic-sold',source:'SYNTHETIC_TEST_ONLY',sourceLocator:'fixture://sale',sourceDigest:digest('sale'),listingState:'SOLD',identity:{productName:values.TITLE,manufacturerBrand:values.BRAND,model:values.MODEL,packCount:1},reviewed:true,reviewReason:null,soldQuantity:3,realizedSoldPrice:20,buyerShipping:0,currency:'USD',lastSoldDate:observed,capturedAt:observed,realizedPriceStatus:'PROVEN'}
 const offer=quantity=>({quantity,price:20,priceReference:digest('sold'),shipping:{...binding,status:'PROVEN',source:'LUNA_SHIPPING_CAPTURE',productId:source.product_id,variantId:source.variant_id,supplierSku:source.sku,quantity,currency:'USD',noPurchase:true,noPayment:true,receiptId:`fixture-shipping-${quantity}`,amountUsd:3},fee:{...binding,status:'PROVEN',accountKey:'fixture-account',productId:source.product_id,variantId:source.variant_id,supplierSku:source.sku,supplierQuantity:quantity,price:20,currency:'USD',receiptId:`fixture-fee-${quantity}`,amountUsd:3},advertising:0,otherCosts:0,costReference:digest('explicit-cost-policy')})
 return {input:{source,opportunityId:'fixture-case',candidateKey:digest('fixture'),accountKey:'fixture-account',corrections,confirmation:{actorId:owner,truthDigest:truth.evidenceDigest},market:[sold],selectedEvidenceIds:[],packReasons:[],offers:[offer(1)],selectedQuantity:1,controlledTest:{},compliance:{...binding,categoryReady:true,specificsReady:true,conditionReady:true,status:'PROVEN'},duplicate:{...binding,status:'PASS'},imageRights:{...binding,status:'AUTHORIZED',assets:[{source:'LUNA',authorized:true,url:'https://cdn.shopify.com/fixture.jpg'}]},finalReview:{},now},offer,binding}
}
test('missing facts stay null, including brand, stock, count, condition and images',()=>{const f=fixture();f.input.source.field_truth_v1=null;f.input.corrections=[];const p=projectFastListingV1(f.input);for(const key of ['BRAND','MODEL','SUPPLIER_STOCK','QUANTITY_OR_SET_COUNT','CONDITION','IMAGES'])assert.equal(p.truth.fields.find(f=>f.FIELD===key).VALUE,null);assert.equal(p.state,'HOLD')})
test('unit is evaluated before any supported pack',()=>{const f=fixture();f.input.packReasons=[{quantity:3,reason:'HUMAN_CONFIRMATION',actorId:owner,truthDigest:f.binding.truthDigest,explanation:'Synthetic bulk use evidence'}];f.input.offers=[f.offer(3),f.offer(1)];assert.deepEqual(projectFastListingV1(f.input).matrix.map(x=>x.quantity),[1,3])})
test('packs without same-presentation evidence or registered human confirmation are absent',()=>{const f=fixture();f.input.offers=[f.offer(1),f.offer(2),f.offer(3),f.offer(4)];assert.deepEqual(projectFastListingV1(f.input).matrix.map(x=>x.quantity),[1]);f.input.packReasons=[{quantity:2,reason:'HUMAN_CONFIRMATION',actorId:owner,truthDigest:f.binding.truthDigest,explanation:'Synthetic evidence'}];assert.deepEqual(projectFastListingV1(f.input).matrix.map(x=>x.quantity),[1,2])})
test('no offer below four dollars can be recommended',()=>{const f=fixture();f.input.offers[0].shipping.amountUsd=10.01;const p=projectFastListingV1(f.input);assert.equal(p.matrix[0].netProfit,2.99);assert.equal(p.matrix[0].recommended,false);assert.ok(p.publishBlockers.includes('NET_PROFIT_BELOW_4'))})
test('margin under 15 percent warns even when four-dollar floor passes',()=>{const f=fixture();f.input.offers[0].price=40;f.input.offers[0].fee.price=40;f.input.offers[0].shipping.amountUsd=28;const o=projectFastListingV1(f.input).matrix[0];assert.equal(o.netProfit,5);assert.deepEqual(o.warnings,['MARGIN_BELOW_15_PERCENT'])})
test('shipping authority is exclusively exact Luna Shipping Capture',()=>{for(const patch of [{source:'ESTIMATE'},{quantity:2},{sourceFingerprint:digest('wrong')},{truthDigest:digest('old')},{freshUntil:observed},{amountUsd:null}]){const f=fixture();Object.assign(f.input.offers[0].shipping,patch);assert.equal(projectFastListingV1(f.input).matrix[0].shipping,null)}})
test('fees consume applicable account/category amount and have no constant fallback',()=>{const f=fixture();f.input.offers[0].fee.amountUsd=7.19;assert.equal(projectFastListingV1(f.input).matrix[0].netProfit,5.81);for(const patch of [{accountKey:'other'},{supplierQuantity:2},{price:21},{receiptId:null},{status:'UNKNOWN'}]){const f=fixture();Object.assign(f.input.offers[0].fee,patch);assert.equal(projectFastListingV1(f.input).matrix[0].netProfit,null)}})
test('unit shipping cannot certify pack shipping; separate receipts have independent costs',()=>{const f=fixture();f.input.packReasons=[{quantity:2,reason:'HUMAN_CONFIRMATION',actorId:owner,truthDigest:f.binding.truthDigest,explanation:'Synthetic reason'}];const pack=f.offer(2);pack.shipping=f.input.offers[0].shipping;f.input.offers.push(pack);assert.equal(projectFastListingV1(f.input).matrix[1].shipping,null);pack.shipping={...pack.shipping,quantity:2,amountUsd:5,receiptId:'fixture-pack'};assert.deepEqual(projectFastListingV1(f.input).matrix.map(o=>o.shipping),[3,5])})
test('active comparables never count as Sold',()=>{const f=fixture();f.input.market[0].listingState='ACTIVE';const p=projectFastListingV1(f.input);assert.equal(p.matrix[0].comparableCount,0);assert.ok(p.listingBlockers.includes('SOLD_EVIDENCE_OR_CONTROLLED_TEST_REQUIRED'))})
test('different included count cannot be an exact comparable',()=>{const f=fixture();f.input.market[0].identity.packCount=2;assert.equal(projectFastListingV1(f.input).comparables[0].classification,'FAMILY');assert.equal(projectFastListingV1(f.input).matrix[0].comparableCount,0)})
test('public Sold displayed price cannot stand in for a realized accepted-offer price',()=>{const f=fixture();f.input.market[0].realizedPriceStatus='UNPROVEN';assert.equal(projectFastListingV1(f.input).matrix[0].comparableCount,0)})
test('CONTROLLED_TEST remains explicit and never claims product proven',()=>{const f=fixture();f.input.market=[];f.input.controlledTest={confirmed:true,actorId:owner,truthDigest:f.binding.truthDigest};const p=projectFastListingV1(f.input);assert.equal(p.marketClassification,'CONTROLLED_TEST');assert.equal(p.productProven,false);assert.equal(p.state,'LISTING_READY')})
test('research drafts can be prepared with visible warnings',()=>{const f=fixture();f.input.confirmation={};f.input.offers[0].shipping={};f.input.offers[0].fee={};f.input.compliance={};const p=projectFastListingV1(f.input);assert.equal(p.state,'RESEARCH_DRAFT');assert.equal(p.canPrepareDraft,true);assert.ok(p.publishBlockers.length>0)})
test('publication stays blocked without identity, stock, shipping, fees or four-dollar profit',()=>{for(const change of [i=>i.confirmation={},i=>{i.source.availability=false;i.source.field_truth_v1.fields.find(f=>f.FIELD==='SUPPLIER_AVAILABILITY').VALUE='OUT_OF_STOCK'},i=>i.offers[0].shipping={},i=>i.offers[0].fee={},i=>i.offers[0].shipping.amountUsd=12]){const f=fixture();change(f.input);assert.notEqual(projectFastListingV1(f.input).state,'PUBLISH_READY')}})
test('exact stock quantity is required for final publication readiness',()=>{const f=fixture();f.input.source.field_truth_v1.fields.find(f=>f.FIELD==='SUPPLIER_STOCK').VALUE=null;assert.ok(projectFastListingV1(f.input).publishBlockers.includes('CONFIRMED_LUNA_STOCK_QUANTITY_REQUIRED'))})
test('final human review is bound to exact facts and offer',()=>{const f=fixture();let p=projectFastListingV1(f.input);f.input.finalReview={actorId:owner,truthDigest:f.binding.truthDigest,offerDigest:digest(p.selected)};p=projectFastListingV1(f.input);assert.equal(p.state,'PUBLISH_READY');f.input.offers[0].shipping.amountUsd=4;assert.notEqual(projectFastListingV1(f.input).state,'PUBLISH_READY')})
test('Sell one like this never replaces own product truth',()=>{const f=fixture(),truth=fastProductTruthV1(f.input.source,[],now);const diff=fastReferenceDifferencesV1({brand:'Competitor',model:'Other',upc:'12345678',quantity:12,description:'Unverified',imageUrls:['competitor']},truth);assert.ok(diff.every(f=>f.importedValue===null));assert.equal(diff.find(f=>f.field==='brand').ownValue,'Fixture Brand');assert.equal(truth.values.QUANTITY_OR_SET_COUNT,1)})
test('unauthorized competitor images block publication and are never importable reference fields',()=>{const f=fixture();f.input.imageRights.assets[0]={source:'COMPETITOR',authorized:false,url:'https://i.ebayimg.com/competitor.jpg'};assert.ok(projectFastListingV1(f.input).publishBlockers.includes('AUTHORIZED_REPRESENTATIVE_IMAGES_REQUIRED'));assert.equal(fastReferenceDifferencesV1({imageUrls:['competitor']},fastProductTruthV1(f.input.source,[],now))[0].classification,'REJECTED')})
test('human corrections retain provenance and superseded receipt rather than rewriting history',()=>{const f=fixture();const correction=validateFastCorrectionV1({field:'MODEL',value:'Confirmed Model',actorId:owner,opportunityId:'fixture-case',sourceFingerprint:f.input.source.source_fingerprint,previous:'old-receipt',now});f.input.corrections=[correction];assert.equal(projectFastListingV1(f.input).identityConfirmed,false);assert.equal(correction.supersedes,'old-receipt');assert.equal(correction.SOURCE,'USER');assert.equal(f.input.source.field_truth_v1.fields.find(f=>f.FIELD==='MODEL').VALUE,'Fixture Model')})
test('facts, quotes and category/image/duplicate authority expire independently',()=>{const f=fixture();f.input.now=new Date(+now+3600001);const p=projectFastListingV1(f.input);assert.equal(p.matrix[0].netProfit,null);assert.notEqual(p.state,'PUBLISH_READY')})
test('contradictions cannot be hidden with raw snapshot fallbacks',()=>{const f=fixture();Object.assign(f.input.source.field_truth_v1.fields.find(f=>f.FIELD==='TITLE'),{SEMANTIC_CLASS:'CONTRADICTED',CONTRADICTION:true,EVIDENCE_STATUS:'CONTRADICTED'});assert.equal(projectFastListingV1(f.input).truth.values.TITLE,undefined)})
test('runtime uses existing engines and certified priority, without marketplace writers',()=>{const runtime=readFileSync('lib/seller-os/fast-listing-runtime-v1.ts','utf8'),shipping=readFileSync('lib/ebay/ebay-luna-chrome-shipping-capture-server-v1.ts','utf8');for(const writer of ['publishOffer(', 'AddFixedPriceItem','ReviseFixedPriceItem','executeAuthorized','executeDraftOnly'])assert.equal(runtime.includes(writer),false);assert.match(shipping,/!batchPriority[\s\S]*resolveFastListingShippingJobsV1/);assert.match(runtime,/readGoldenPresaleAuthorityV1/);assert.match(runtime,/create_or_reuse_quick_pick_product_research_plan_v2/);assert.match(runtime,/existingPackageProtected:true/);assert.equal(projectFastListingV1(fixture().input).safety.marketplaceWrites,0)})
test('canonical owner base count is reused without transferring visual markings into manufacturer brand',()=>{
 const source={product_id:'123',variant_id:'456',sku:'FIXTURE',canonical_url:'https://lunaportex.com/products/fixture',source_fingerprint:digest('fixture'),observed_at:observed}
 const evidence=buildGoldenOwnerProductTruthEvidenceV1({candidate:{productId:'123',variantId:'456',supplierSku:'FIXTURE',supplierQuantity:1},accountKey:'fixture-account',ownerUserId:owner,sourceFingerprint:source.source_fingerprint,expectedCanonicalUrl:source.canonical_url,source:{canonicalUrl:source.canonical_url,sourceLocator:source.canonical_url,sourceDigest:digest('image'),capturedAt:observed,sourceMediaType:'IMAGE'},observations:[{factClass:'SUPPLIER_BASE_INCLUDED_UNIT_COUNT',value:'2',evidenceStatement:'Synthetic owner observed two included pieces.'},{factClass:'VISIBLE_BRAND_MARKING',value:'Fixture Logo',evidenceStatement:'Synthetic visible marking; not manufacturer authority.'}],operatorAttested:true,now})
 source.canonicalOwnerTruth={accountKey:'fixture-account',ownerId:owner,evidence}
 let truth=fastProductTruthV1(source,[],now)
 assert.equal(truth.values.QUANTITY_OR_SET_COUNT,2);assert.equal(truth.values.BRAND,undefined)
 assert.equal(truth.fields.find(f=>f.FIELD==='QUANTITY_OR_SET_COUNT').METHOD,'OWNER_ATTESTED_SUPPLIER_VISUAL_OBSERVATION')
 source.canonicalOwnerTruth.ownerId='other-owner';truth=fastProductTruthV1(source,[],now);assert.equal(truth.values.QUANTITY_OR_SET_COUNT,undefined)
})
test('Sold pack matrix reuses the shared reviewed demand policy and excludes unsupported sizes',()=>{
 const f=fixture();f.input.market=[{...f.input.market[0],identity:{...f.input.market[0].identity,packCount:2}}]
 f.input.offers=[f.offer(4),f.offer(2),f.offer(1),f.offer(3)]
 assert.deepEqual(projectFastListingV1(f.input).matrix.map(o=>o.quantity),[1,2])
 f.input.market[0].reviewed=false;assert.deepEqual(projectFastListingV1(f.input).matrix.map(o=>o.quantity),[1])
})
test('a comparable without proven pack quantity never contributes to price or market readiness',()=>{
 const f=fixture();f.input.market[0].identity.packCount=null
 assert.equal(projectFastListingV1(f.input).matrix[0].comparableCount,0)
})
