import test from 'node:test'
import assert from 'node:assert/strict'
import {readFileSync} from 'node:fs'
import {PGlite} from '@electric-sql/pglite'

const migration=readFileSync('supabase/migrations/20261004041111_seller_os_fast_listing_v1.sql','utf8')
const account='fixture:'+'a'.repeat(64),owner='10000000-0000-4000-8000-000000000001',snapshot='20000000-0000-4000-8000-000000000001'
async function fixture(){
 const db=new PGlite()
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
 create schema auth;create table auth.users(id uuid primary key);
 create table public.luna_catalog_snapshots_v1(snapshot_id uuid primary key,snapshot_status text);
 create table public.luna_catalog_snapshot_variants_v1(snapshot_id uuid,product_id text,variant_id text,sku text,title text,price numeric,availability boolean,observed_at timestamptz,canonical_url text,field_truth_v1 jsonb);
 create table public.ebay_luna_opportunity_queue(id uuid primary key default gen_random_uuid(),candidate_key text unique,supplier_product_id text,supplier_variant_id text,supplier_sku text,product_title text,queue_status text,decision text,supplier_price numeric,supplier_available boolean,supplier_snapshot_at timestamptz,assessment jsonb,first_detected_at timestamptz default now());
 create table public.seller_os_operational_learning_ledger_v1(marketplace_account_key text,failure_class text,invariant_code text,mechanism_version text,evidence_fingerprint text,recovery_policy_version text,retry_safety text,recovery_class text,recovery_outcome text,regression_guard jsonb,evidence jsonb,status text,first_observed_at timestamptz,last_observed_at timestamptz,resolved_at timestamptz,unique(marketplace_account_key,invariant_code,evidence_fingerprint,mechanism_version));
 create table public.ebay_luna_opportunity_queue_events(id uuid primary key default gen_random_uuid(),opportunity_id uuid,event_type text,old_value jsonb,new_value jsonb,idempotency_key text unique);
 create function public.seller_os_current_commercial_candidate_id_v1(text,text,text,text,text,text) returns text language sql immutable as $$select 'sha256:'||repeat('b',64)$$;
 grant select,insert on public.seller_os_operational_learning_ledger_v1,public.ebay_luna_opportunity_queue,public.ebay_luna_opportunity_queue_events to service_role;
 grant select on public.luna_catalog_snapshot_variants_v1,public.luna_catalog_snapshots_v1 to service_role;`)
 await db.exec(migration)
 await db.exec(readFileSync("supabase/migrations/20261004044126_seller_os_fast_listing_intake_column_repair_v1.sql","utf8"))
 await db.query('insert into auth.users values($1)',[owner]);await db.query("insert into luna_catalog_snapshots_v1 values($1,'COMPLETE')",[snapshot])
 await db.query("insert into luna_catalog_snapshot_variants_v1 values($1,'fixture-product','fixture-variant','FIXTURE-ONLY','Synthetic pet product',4,true,now(),'https://lunaportex.com/products/fixture-only',null)",[snapshot])
 const ensure=async()=>(await db.query('select public.ensure_seller_os_fast_listing_v1($1,$2,$3,$4,$5,$6) as result',[account,owner,snapshot,'fixture-product','fixture-variant','FIXTURE-ONLY'])).rows[0].result
 const claim=async(id,key,token)=>(await db.query("select public.claim_seller_os_fast_listing_v1($1,$2,$3,'PREPARE',$4,$5) as result",[account,owner,id,key,token])).rows[0].result
 const write=async(id,revision,key,token=null)=>(await db.query("select public.write_seller_os_fast_listing_v1($1,$2,$3,$4,$5,'PREPARE',$6,$7,$8) as result",[account,owner,id,revision,key,JSON.stringify({packageId:'synthetic-package'}),JSON.stringify({state:'RESEARCH_DRAFT',learningEvidenceDigest:'sha256:'+'a'.repeat(64)}),token])).rows[0].result
 return{db,ensure,claim,write}
}
test('selected Luna product reuses category canonical case without changing certified plan or approvals',async()=>{const f=await fixture();try{
 const original='30000000-0000-4000-8000-000000000001';await f.db.query("insert into ebay_luna_opportunity_queue(id,candidate_key,supplier_product_id,supplier_variant_id,supplier_sku,assessment) values($1,'category-candidate','fixture-product','fixture-variant','FIXTURE-ONLY',$2)",[original,JSON.stringify({certifiedPlan:{protected:true},humanApproval:'preserved'})])
 const a=await f.ensure(),b=await f.ensure();assert.equal(a.opportunity.id,original);assert.equal(b.opportunity.id,original);assert.deepEqual(b.opportunity.assessment,{certifiedPlan:{protected:true},humanApproval:'preserved'});assert.equal((await f.db.query('select count(*)::int n from ebay_luna_opportunity_queue')).rows[0].n,1);assert.equal((await f.db.query('select count(*)::int n from seller_os_fast_listing_contexts_v1')).rows[0].n,1)
 }finally{await f.db.close()}})
test('second execution cannot duplicate case, lease, event or prepared work',async()=>{const f=await fixture();try{const a=await f.ensure(),b=await f.ensure();assert.equal(a.opportunity.id,b.opportunity.id);const token='40000000-0000-4000-8000-000000000001',second='40000000-0000-4000-8000-000000000002';assert.equal((await f.claim(a.opportunity.id,'same-work',token)).claimed,true);assert.equal((await f.claim(a.opportunity.id,'same-work',second)).claimed,false);await f.write(a.opportunity.id,0,'same-work',token);assert.equal((await f.claim(a.opportunity.id,'same-work',second)).completed,true);assert.equal((await f.write(a.opportunity.id,0,'same-work',token)).revision,1);assert.equal((await f.db.query('select count(*)::int n from ebay_luna_opportunity_queue_events')).rows[0].n,1)}finally{await f.db.close()}})
test('stuck worker recovers with one current lease, stale completion rejected and retries bounded',async()=>{const f=await fixture();try{const a=await f.ensure(),id=a.opportunity.id,t1='40000000-0000-4000-8000-000000000001',t2='40000000-0000-4000-8000-000000000002';await f.claim(id,'recover-work',t1);await f.db.exec("update seller_os_fast_listing_contexts_v1 set lease_expires_at=now()-interval '1 second'");const recovered=await f.claim(id,'recover-work',t2);assert.equal(recovered.claimed,true);assert.equal(recovered.context.attempt_count,2);await assert.rejects(f.write(id,0,'stale-completion',t1),/LEASE_CONFLICT/);await f.write(id,0,'recover-work',t2);assert.equal((await f.claim(id,'recover-work',t1)).completed,true);
 await f.claim(id,'fails-three-times',t1);for(let i=0;i<2;i++){await f.db.exec("update seller_os_fast_listing_contexts_v1 set lease_expires_at=now()-interval '1 second'");await f.claim(id,'fails-three-times',t1)}await f.db.exec("update seller_os_fast_listing_contexts_v1 set lease_expires_at=now()-interval '1 second'");await assert.rejects(f.claim(id,'fails-three-times',t1),/RETRY_EXHAUSTED/);assert.equal((await f.db.query('select count(*)::int n from ebay_luna_opportunity_queue_events')).rows[0].n,1)
 }finally{await f.db.close()}})
test('owner scope, optimistic revision, immutable history and Data API ACL enforce safe corrections',async()=>{const f=await fixture();try{const a=await f.ensure(),id=a.opportunity.id;await f.write(id,0,'first-event');await assert.rejects(f.write(id,0,'stale-revision'),/REVISION_CONFLICT/);await assert.rejects(f.db.exec("update ebay_luna_opportunity_queue_events set new_value='{}'"),/IMMUTABLE/);await assert.rejects(f.db.exec('delete from ebay_luna_opportunity_queue_events'),/IMMUTABLE/);assert.equal((await f.db.query('select count(*)::int n from seller_os_operational_learning_ledger_v1')).rows[0].n,1);const acl=(await f.db.query("select has_table_privilege('anon','public.seller_os_fast_listing_contexts_v1','SELECT') as anon_read,has_function_privilege('authenticated','public.claim_seller_os_fast_listing_v1(text,uuid,uuid,text,text,uuid)','EXECUTE') as auth_execute")).rows[0];assert.equal(acl.anon_read,false);assert.equal(acl.auth_execute,false);await f.db.exec('set role service_role');assert.equal((await f.ensure()).opportunity.id,id)}finally{await f.db.close()}})
