import test from "node:test"
import assert from "node:assert/strict"
import { readFileSync } from "node:fs"
import { diagnoseListingTreatmentV1, promotionProfitGuardV1, promotionPortfolioPreviewV1, projectListingMetricsV1,
  validatePromotionPolicyV1, compareTreatmentReceiptV1, FRIENDLY_ACTIONS } from "./listing-treatment-engine-v1.ts"
const id = "366643122092"
const amount = value => ({ value, reference: "proven:" + value, fresh: true })
const economics = () => ({ salePrice: amount(100), productCost: amount(30), shippingCost: amount(10), ebayFees: amount(15), otherCosts: amount(0), adFeeBasis: amount(120) })
const policy = { mode: "MANUAL", minRate: 3, maxRate: 5, minProfit: 8, minMargin: 15, window: "NOW", timeZone: "America/Los_Angeles", startsAt: null, endsAt: null }
const comparison = { itemId: id, window: "7D", basis: "OWN_HISTORY", reference: "baseline:1", sampleRuleReference: "contract:sample:1", sufficient: true, fresh: true, traffic: "LOW", ctr: "HEALTHY", conversion: "HEALTHY" }
const input = () => ({ itemId: id, window: "7D", comparison: { ...comparison }, economics: economics(), policy, stock: "AVAILABLE", stockReference: "stock:1", protected: false, qualityReferences: ["quality:1"], keywordReferences: ["keyword:v2.1"] })
test("LOW_TRAFFIC_GOOD_CONVERSION_SCALE_PASS", () => assert.equal(diagnoseListingTreatmentV1(input()).treatment, "SCALE"))
test("HIGH_TRAFFIC_LOW_CTR_OPTIMIZE_PASS", () => { const i=input(); i.comparison.traffic="HIGH"; i.comparison.ctr="LOW"; const r=diagnoseListingTreatmentV1(i); assert.equal(r.treatment,"OPTIMIZE"); assert.ok(r.diagnosticPriorities.includes("MAIN_IMAGE")); assert.ok(r.supportingEvidence.includes("quality:1")) })
test("GOOD_CTR_LOW_CONVERSION_OPTIMIZE_PASS", () => { const i=input(); i.comparison.conversion="LOW"; const r=diagnoseListingTreatmentV1(i); assert.equal(r.treatment,"OPTIMIZE"); assert.ok(r.diagnosticPriorities.includes("SHIPPING")) })
test("LOW_MARGIN_PROFIT_PROTECT_PASS", () => { const i=input(); i.economics.productCost=amount(80); assert.equal(diagnoseListingTreatmentV1(i).treatment,"PROFIT_PROTECT") })
test("LOW_STOCK_RESTOCK_PASS", () => { const i=input(); i.stock="LOW"; assert.equal(diagnoseListingTreatmentV1(i).treatment,"RESTOCK"); assert.equal(promotionPortfolioPreviewV1([diagnoseListingTreatmentV1(i)]).ready,0) })
test("INSUFFICIENT_SAMPLE_TEST_PASS", () => { for (const change of [{sufficient:false}, {fresh:false}, {reference:""}, {sampleRuleReference:""}, {itemId:"366582671136"}, {window:"24H"}]) { const i=input(); Object.assign(i.comparison,change); assert.equal(diagnoseListingTreatmentV1(i).treatment,"TEST") } })
test("METRICS_FIRST_TREATMENT_PASS", () => { const i=input(); i.comparison=null; assert.equal(diagnoseListingTreatmentV1(i).treatment,"TEST"); assert.deepEqual(diagnoseListingTreatmentV1(i).diagnosticPriorities,[]) })
test("ECONOMIC_CEILING_PASS", () => { const r=promotionProfitGuardV1(economics(),{...policy,maxRate:90}); assert.equal(r.maxSafeAdRate,25); assert.equal(r.projectedAdCost,30); assert.equal(r.projectedProfitAfterAds,15); assert.equal(r.projectedMarginAfterAds,15) })
test("UNSAFE_AD_RATE_BLOCKED_PASS", () => { assert.equal(promotionProfitGuardV1(economics(),{...policy,minRate:26,maxRate:30}).status,"BLOCKED_MARGIN"); const e=economics(); e.adFeeBasis=amount(null); assert.equal(promotionProfitGuardV1(e,policy).status,"BLOCKED_EVIDENCE"); e.otherCosts.fresh=false; assert.equal(promotionProfitGuardV1(e,policy).profitBeforeAds,null) })
test("profit guard never exceeds either floor across cents and fee bases", () => { for(let price=11;price<250;price+=7.13) { const e=economics(); e.salePrice=amount(price); e.adFeeBasis=amount(price*1.15); const r=promotionProfitGuardV1(e,{...policy,maxRate:80}); if(r.status==="SIMULATION_READY") { assert.ok(r.projectedProfitAfterAds>=policy.minProfit); assert.ok(r.projectedMarginAfterAds>=policy.minMargin); assert.ok(r.recommendedAdRate<=r.maxSafeAdRate) } } })
test("MULTI_LISTING_POLICY_PREVIEW_PASS", () => { const a=diagnoseListingTreatmentV1(input()), b={...a,itemId:"366582671136"}; assert.equal(promotionPortfolioPreviewV1([a,b]).ready,2); assert.throws(()=>promotionPortfolioPreviewV1([a,a])); assert.throws(()=>promotionPortfolioPreviewV1(Array.from({length:21},(_,i)=>({...a,itemId:String(i)})))) })
test("MISSING_METRICS_NOT_INVENTED and exact windows", () => { const observation={value:100,availability:"AVAILABLE",identity:{itemId:id},source:{evidenceReference:"m:1"},reportingWindow:{start:"2026-09-01T00:00:00Z",end:"2026-09-08T00:00:00Z",timeZone:"UTC"},freshness:{status:"FRESH"}}; const listing={identity:{itemId:id,startTime:null},stock:{quantity:null},metrics:{impressions:observation}}; const r=projectListingMetricsV1(listing); assert.equal(r.windows["7D"].impressions.value,100); assert.equal(r.windows["24H"].impressions.value,null); assert.equal(r.windows["30D"].impressions.value,null); assert.equal(r.windows["7D"].clicks,null); observation.identity.itemId="other"; assert.equal(projectListingMetricsV1(listing).windows["7D"].impressions.value,null) })
test("TREATMENT_RECEIPT_PASS",()=>{const a={itemId:id,window:"7D",values:{ctr:2,conversion:null},reference:"before",start:"2026-09-01",end:"2026-09-08"}; const b={...a,values:{ctr:3,conversion:1},reference:"after",start:"2026-09-08",end:"2026-09-15"}; const r=compareTreatmentReceiptV1(a,b); assert.equal(r.outcomes.ctr,"IMPROVED"); assert.equal(r.outcomes.conversion,"INSUFFICIENT_EVIDENCE"); assert.equal(r.causalAttribution,false); assert.equal(compareTreatmentReceiptV1(a,{...b,itemId:"other"}).outcomes.ctr,"INSUFFICIENT_EVIDENCE")})
test("explicit timezone and weekend validation",()=>{assert.throws(()=>validatePromotionPolicyV1({...policy,timeZone:""}));assert.throws(()=>validatePromotionPolicyV1({...policy,window:"WEEKEND"})); assert.equal(validatePromotionPolicyV1({...policy,window:"WEEKEND",startsAt:"2026-09-12T00:00:00-07:00",endsAt:"2026-09-14T00:00:00-07:00"}).window,"WEEKEND")})
test("FRIENDLY_MENU_PASS and NO_MARKETPLACE_WRITE_PASS",()=>{ assert.equal(FRIENDLY_ACTIONS.length,4); const r=diagnoseListingTreatmentV1(input()); assert.equal(r.safety.marketplaceWrites,0); assert.equal(r.safety.ebayAdsWriteEnabled,false); const route=readFileSync(new URL("../../app/api/admin/ebay/assistant/revenue-engine/route.ts",import.meta.url),"utf8"); assert.ok(!route.includes("applyEbay")); assert.ok(route.includes("seller_os_user")); assert.ok(route.includes("seller_os_dedicated_preprod")) })
