import test from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { projectLunaShippingCaptureCapabilityV1 } from './luna-shipping-capture-capability-v1.ts'
const now=new Date('2026-09-10T12:00:00Z')
const event=(state,extra={})=>({state,success:true,timestamp:'2026-09-10T11:59:00Z',traceId:'SYNTHETIC_TRACE',...extra})
const complete=()=>['CANONICAL_DESTINATION_MATCH','SHIPPING_PARSED','DURABLE_READBACK'].map(s=>event(s))
const project=(events,extra={})=>projectLunaShippingCaptureCapabilityV1({connected:true,traceAvailable:true,events,now,...extra})
test('CONNECTED != CAPTURE_CAPABLE; heartbeat and queue never prove shipping',()=>{for(const events of [[],[event('BRIDGE_CONNECTED')],[event('PRODUCTION_WORKER_READY')]]){const r=project(events);assert.equal(r.connected,true);assert.equal(r.captureCapable,false);assert.equal(r.label,'LIMITADA TEMPORALMENTE');assert.equal(r.shippingCostProvenByConnection,false)}})
test('current complete capture is separate from connection and scoped to one trace',()=>{assert.equal(project(complete()).label,'CAPTURA DISPONIBLE');assert.equal(project(complete(),{connected:false}).captureCapable,false);assert.equal(project(complete(),{traceAvailable:false}).captureCapable,false);const mixed=complete();mixed[1].traceId='OTHER';assert.equal(project(mixed).captureCapable,false)})
test('stale, future or failed captures cannot advertise readiness',()=>{assert.equal(project(complete().map(e=>({...e,timestamp:'2026-09-09T12:00:00Z'}))).captureCapable,false);assert.equal(project(complete().map(e=>({...e,timestamp:'2026-09-11T12:00:00Z'}))).captureCapable,false);assert.equal(project([...complete(),event('FAIL',{success:false,timestamp:now.toISOString()})]).captureCapable,false)})
test('capability presentation introduces no poller, supplier request or implicit quote',()=>{const source=readFileSync(new URL('./luna-shipping-capture-capability-v1.ts',import.meta.url),'utf8');assert.doesNotMatch(source,/fetch\(|setInterval\(|setTimeout\(/);const home=readFileSync(new URL('../../app/admin/seller-os-home-dashboard-v1.tsx',import.meta.url),'utf8');assert.match(home,/captureCapabilityProven === true/);assert.match(home,/La conexión no confirma una captura/);const mayel=readFileSync(new URL('../../app/admin/ebay/mayel/ads-activation-preview.tsx',import.meta.url),'utf8');assert.match(mayel,/La conexión con Luna no confirma el costo/);assert.match(mayel,/row.shippingStatus === "SHIPPING_PROVEN"/)})
