import test from 'node:test'
import assert from 'node:assert/strict'
import {publicationFeeStructureV1 as fee,publicationEconomicsV1 as economics} from './publication-fee-structure-v1.ts'
import {currentPrepublicationProofV1 as proof,knownPublicationPayloadErrorsV1 as payloadErrors,knownBuyerShippingV1} from './publication-prevalidation-boundary-v1.ts'
import {keywordWireDigestV1 as digest} from './keyword-intelligence-handoff-v1.ts'
import {consumeListingFeeAuthorityV1} from './listing-fee-authority-v1.ts'
const now=new Date('2026-09-11T14:00:00Z')
function fees(){
 const freshness={observedAt:'2026-09-11T13:50:00Z',freshUntil:'2026-09-11T15:00:00Z'}
 const components=['FINAL_VALUE_PERCENT','PER_ORDER','SELLER_PERFORMANCE','SERVICE_METRICS','INTERNATIONAL','CURRENCY_CONVERSION','REGULATORY_OPERATING','TAX_ON_FEES'].map(type=>({type,source:'https://www.ebay.com',status:['FINAL_VALUE_PERCENT','SERVICE_METRICS','INTERNATIONAL'].includes(type)?'PENDING_ORDER_CONTEXT':type==='PER_ORDER'?'PROVEN':'NOT_APPLICABLE',amount:type==='PER_ORDER'?.4:['FINAL_VALUE_PERCENT','SERVICE_METRICS','INTERNATIONAL'].includes(type)?null:0,pendingDependency:null}))
 const a={...freshness,contractVersion:'SELLER_OS_EBAY_FEE_AUTHORITY_V1',state:'PENDING_ORDER_CONTEXT',marketplaceAccountKey:'acct',packageId:'pkg',sku:'sku',categoryId:'cat',itemId:null,marketplace:'EBAY_US',packageRevision:'rev',basePreSaleFeeProven:true,components,preSaleSourceContextV1:{accountPerformance:{registrationCountry:'US'},listing:{price:17.77},categoryFeePolicy:{policy:{...freshness,marketplaceAccountKey:'acct',packageId:'pkg',packageRevision:'rev',sku:'sku',categoryIds:['cat'],currency:'USD',sourceVersion:'version',reference:'ref',tierMethod:'WHOLE_AMOUNT',tiers:[{upTo:5000,ratePct:15},{upTo:null,ratePct:9}]}}}}
 return {authority:a,subjectMatched:true,accountKey:'acct',packageId:'pkg',sku:'sku',categoryId:'cat',salePrice:17.77,buyerShipping:0,now}
}
export function validation(){
 const preview={sku:'sku',inventoryItemPayload:{condition:'NEW',product:{title:'Own bracelet',description:'Own evidence',aspects:{Brand:['Unbranded']},imageUrls:['https://example.com/own.jpg']}},offerPayload:{sku:'sku',marketplaceId:'EBAY_US',format:'FIXED_PRICE',categoryId:'261987',availableQuantity:1,merchantLocationKey:'location',pricingSummary:{price:{value:'17.77',currency:'USD'}},listingPolicies:{paymentPolicyId:'p',returnPolicyId:'r',fulfillmentPolicyId:'f'}}}
 const r={packageHash:'hash',packageGeneration:'generation',previewHash:digest(preview),preview}
 const p={id:'pub',listing_package_id:'pkg',marketplace_account_key:'acct',sku:'sku',offer_id:'offer',draft_execution_id:'execution',phase:'preview_ready',listing_id:null,publication_idempotency_key:null,preparation:{current:r}}
 const v={version:'SELLER_OS_PREPUBLICATION_ATTAINABLE_EVIDENCE_V1',binding:{publicationId:'pub',packageId:'pkg',accountKey:'acct',sku:'sku',offerId:'offer',draftExecutionId:'execution',packageHash:'hash',packageGeneration:'generation',previewGeneration:'generation',previewHash:digest(preview)},observedAt:now.toISOString(),checks:Object.fromEntries(['currentOfferReadbackPass','currentInventoryReadbackPass','currentPolicyReadbackPass','currentFeesRequestPass','prepublicationContractValidationPass','currentTaxonomyPass','currentAccountPass','currentImageAuthorityPass'].map(k=>[k,true])),fullOfficialDryRunAvailable:false,publishTimeOnlyValidationRequired:true,ebayPrevalidationPass:false,publicationAuthorized:false,blockingErrors:[],warnings:[]}
 return {p,v,preview}
}
test('Tax contingent structure never assigns zero or an absolute ceiling',()=>{const r=fee(fees());assert.equal(r.feeAuthorityReady,true);assert.equal(r.deterministicPreSaleEbayFees,3.07);assert.equal(r.feeSafeBound,null);assert.equal(r.buyerTaxAssumedZero,false);assert.equal(r.contingentPostOrderFeeComponents[0].amount,null);assert.equal(r.postOrderFeeReconciliationRequired,true)})
test('Unknown category service applicability reserves official maximum; does not transfer other category rating',()=>{const r=fee(fees());assert.equal(r.preSaleRiskReserves[0].amount,1.07);assert.equal(r.preSaleRiskReserves[0].applicability,'UNPROVEN_RESERVED_AT_OFFICIAL_MAXIMUM')})
for(const type of ['SELLER_PERFORMANCE','CURRENCY_CONVERSION','REGULATORY_OPERATING','TAX_ON_FEES'])test(`Missing knowable ${type} remains blocked`,()=>{const i=fees();i.authority.components.find(c=>c.type===type).status='PENDING_AUTHORITY';assert.equal(fee(i).feeAuthorityReady,false)})
for(const k of ['accountKey','packageId','sku','categoryId'])test(`Wrong fee ${k} fails closed`,()=>{const i=fees();i[k]='other';assert.equal(fee(i).feeAuthorityReady,false)})
test('Stale and price-mismatched fees remain blocked',()=>{const i=fees();i.authority.freshUntil='2026-09-11T13:00:00Z';assert.equal(fee(i).feeAuthorityReady,false);const j=fees();j.salePrice=18;assert.equal(fee(j).feeAuthorityReady,false)})
test('Missing buyer shipping is not zero',()=>{const i=fees();i.buyerShipping=null;assert.equal(fee(i).feeAuthorityReady,false)})
test('Publication structure does not satisfy Ads monetary authority',()=>{const i=fees();const r=fee(i);assert.equal(r.adsEconomicsProven,false);assert.equal(consumeListingFeeAuthorityV1({...i,metadata:{feeAuthorityV1:r}}).status,'NEEDS_EVIDENCE')})
test('Economics separates deterministic profit from reserves and unknown actual result',()=>{const r=economics({fee:fee(fees()),salePrice:17.77,productCost:1.06,shipping:6.99,otherCosts:0,listingFees:.35,materialCostsProven:true});assert.equal(r.deterministicProfitBeforePostOrderAdjustments,6.65);assert.equal(r.budgetedProfitBeforePostOrderAdjustments,4.93);assert.equal(r.profitAfterAllActualFees,null);assert.equal(r.absoluteProfitGuaranteed,false)})
test('Missing known cost remains blocked',()=>assert.equal(economics({fee:fee(fees()),salePrice:17.77,productCost:null,shipping:6.99,otherCosts:0,listingFees:.35,materialCostsProven:true}).economicsProven,false))
test('CURRENT attainable evidence valid without falsely claiming eBay full dry run',()=>{const {p,v}=validation();assert.equal(proof(p,v,now),true);v.ebayPrevalidationPass=true;assert.equal(proof(p,v,now),false)})
for(const k of ['publicationId','packageId','accountKey','sku','offerId','draftExecutionId','packageHash','packageGeneration','previewHash','previewGeneration'])test(`Receipt wrong ${k} cannot authorize CURRENT readiness`,()=>{const {p,v}=validation();v.binding[k]='old';assert.equal(proof(p,v,now),false)})
test('ACK only, missing readback and stale proof fail closed',()=>{const {p,v}=validation();assert.equal(proof(p,{state:'ACK'},now),false);v.checks.currentOfferReadbackPass=false;assert.equal(proof(p,v,now),false);v.checks.currentOfferReadbackPass=true;assert.equal(proof(p,v,new Date('2026-09-11T14:11:00Z')),false)})
test('Unknown commit and claimed publication cannot be READY via preparation proof',()=>{const {p,v}=validation();p.phase='outcome_unknown';assert.equal(proof(p,v,now),false);p.phase='preview_ready';p.publication_idempotency_key='claimed';assert.equal(proof(p,v,now),false)})
test('Known errors and unclassified warnings block, publish-time only is explicit',()=>{const {p,v}=validation();v.warnings=[{code:'material'}];assert.equal(proof(p,v,now),false);v.warnings=[];v.blockingErrors=['missing'];assert.equal(proof(p,v,now),false)})
test('Local required fields cannot be substituted by HTTP success',()=>{const {preview}=validation();assert.deepEqual(payloadErrors(preview),[]);delete preview.inventoryItemPayload.condition;assert.ok(payloadErrors(preview).includes('CONDITION_REQUIRED'))})
test('Supplier shipping is not buyer shipping authority',()=>{assert.equal(knownBuyerShippingV1({shippingAmount:6.99}),null);assert.equal(knownBuyerShippingV1({source:'OFFICIAL_EBAY_FULFILLMENT_POLICY',marketplaceId:'EBAY_US',shippingOptions:[{optionType:'DOMESTIC',costType:'FLAT_RATE',shippingServices:[{freeShipping:true,shippingCost:{currency:'USD',value:'0'}}]}]}),0)})
