export type RevenueDependencyStageV1 = "INPUT_VALIDATION" | "EXACT_LISTING_IDENTITY" |
  "LISTING_QUALITY_PROJECTION" | "KEYWORD_INTELLIGENCE" | "PACKAGE_PREVIEW" |
  "IMAGE_REQUEST_VALIDATION" | "IMAGE_SOURCE" | "IMAGE_PROVIDER" | "IMAGE_QA" |
  "IMAGE_PERSISTENCE" | "ASSISTANT_EVIDENCE" | "ASSISTANT_RELAY" | "COPILOT"

const stages = new Set<RevenueDependencyStageV1>(["INPUT_VALIDATION", "EXACT_LISTING_IDENTITY",
  "LISTING_QUALITY_PROJECTION", "KEYWORD_INTELLIGENCE", "PACKAGE_PREVIEW",
  "IMAGE_REQUEST_VALIDATION", "IMAGE_SOURCE", "IMAGE_PROVIDER", "IMAGE_QA",
  "IMAGE_PERSISTENCE", "ASSISTANT_EVIDENCE", "ASSISTANT_RELAY", "COPILOT"])
const knownCodes = new Set([
  "EXACT_PRODUCT_TRUTH_LINKAGE_REQUIRED", "FULL_RESOLUTION_SOURCE_UNAVAILABLE", "SELLER_OS_VISUAL_VARIANT_PROVIDER_OUTPUT_INVALID", "SELLER_OS_VISUAL_VARIANT_PROVIDER_RESPONSE_TOO_LARGE", "VISUAL_EXPERIMENT_SAFETY_GUARD_BLOCKED", "VISUAL_VARIANT_ACTIVE_COUNT_FAILED", "VISUAL_VARIANT_ACTIVE_LIMIT_REACHED", "VISUAL_VARIANT_BACKGROUND_QA_REJECTED", "VISUAL_VARIANT_BUDGET_USAGE_PERSIST_FAILED", "VISUAL_VARIANT_COUNT_OUT_OF_BOUNDS", "VISUAL_VARIANT_DAILY_BUDGET_READ_FAILED", "VISUAL_VARIANT_DAILY_CALL_LIMIT_REACHED", "VISUAL_VARIANT_EXPERIMENT_PERSIST_FAILED", "VISUAL_VARIANT_GENERATION_REASON_UNPROVEN", "VISUAL_VARIANT_MATERIAL_REASON_REQUIRED", "VISUAL_VARIANT_MONTHLY_BUDGET_BLOCKED", "VISUAL_VARIANT_MONTHLY_BUDGET_READ_FAILED", "VISUAL_VARIANT_NOT_ACTIONABLE", "VISUAL_VARIANT_PRIVATE_UPLOAD_FAILED", "VISUAL_VARIANT_PRODUCT_TRUTH_REJECTED", "VISUAL_VARIANT_PROVIDER_CONFIGURATION_INVALID", "VISUAL_VARIANT_READ_FAILED",
  "LISTING_OPTIMIZATION_INPUT_INVALID", "VISUAL_VARIANT_CREATE_INVALID",
  "FULL_RESOLUTION_SOURCE_UNAVAILABLE", "IMAGE_SOURCE_TRANSPORT_FAILED",
  "IMAGE_PROVIDER_TRANSPORT_FAILED", "SELLER_OS_VISUAL_VARIANT_PROVIDER_OUTPUT_INVALID",
  "SELLER_OS_VISUAL_VARIANT_PROVIDER_RESPONSE_TOO_LARGE", "VISUAL_VARIANT_BACKGROUND_QA_REJECTED",
  "VISUAL_VARIANT_PRODUCT_TRUTH_REJECTED", "VISUAL_VARIANT_PRIVATE_UPLOAD_FAILED",
  "VISUAL_VARIANT_EXPERIMENT_PERSIST_FAILED", "VISUAL_VARIANT_BUDGET_USAGE_PERSIST_FAILED",
  "SELLER_OS_VISUAL_VARIANT_FAILED", "EXACT_PRODUCT_TRUTH_LINKAGE_REQUIRED",
  "VISUAL_VARIANT_MONTHLY_BUDGET_BLOCKED", "VISUAL_VARIANT_DAILY_CALL_LIMIT_REACHED",
  "VISUAL_VARIANT_PROVIDER_CONFIGURATION_INVALID", "VISUAL_VARIANT_GENERATION_REASON_UNPROVEN",
  "SELLER_OS_EVIDENCE_READ_FAILED_CLOSED", "SELLER_OS_AUDIT_READ_FAILED_CLOSED",
  "SELLER_OS_TOOL_FAILED_CLOSED", "COPILOT_EVIDENCE_READ_FAILED_CLOSED",
  "SELLER_OS_CLOUD_READ_RELAY_SOURCE_READ_FAILED", "SELLER_OS_CLOUD_READ_RELAY_TRANSPORT_FAILED",
  "SELLER_OS_PRODUCT_CASE_UNEXPECTED_EXCEPTION", "QUALITY_REPORT_READ_UNAVAILABLE",
  "EXACT_LISTING_LINK_AMBIGUOUS", "EXACT_LISTING_LINK_TARGET_UNPROVEN",
  "CANONICAL_PRODUCT_IDENTITY_NOT_FOUND", "KEYWORD_DECISION_UNPROVEN",
  "PACKAGE_PREVIEW_EVIDENCE_REQUIRED", "EBAY_IMAGE_PIPELINE_FAILED",
])
export function revenueTraceIdV1(value?: unknown): string {
  return typeof value === "string" && /^[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$/i.test(value)
    ? value : crypto.randomUUID()
}
function allowedCode(value: unknown): value is string {
  return typeof value === "string" && (knownCodes.has(value) ||
    /^SELLER_OS_VISUAL_VARIANT_PROVIDER_HTTP_[45]\d{2}$/.test(value))
}
export function revenueFailureV1(error: unknown, stage: RevenueDependencyStageV1,
  fallback: string, traceId?: string) {
  const raw = error && typeof error === "object" ? error as Record<string, unknown> : {}
  const code = raw.ERROR_CODE ?? (error instanceof Error ? error.message : null)
  const dependency = stages.has(raw.DEPENDENCY_STAGE as RevenueDependencyStageV1)
    ? raw.DEPENDENCY_STAGE as RevenueDependencyStageV1 : stage
  return Object.freeze({ ERROR_CODE: allowedCode(code) ? code : fallback,
    DEPENDENCY_STAGE: dependency,
    TRACE_ID: revenueTraceIdV1(raw.TRACE_ID ?? traceId),
    ...(typeof raw.PROVIDER_REQUEST_ID === "string" && /^req_[a-zA-Z0-9_-]{8,120}$/.test(raw.PROVIDER_REQUEST_ID)
      ? { PROVIDER_REQUEST_ID: raw.PROVIDER_REQUEST_ID } : {}),
    FAIL_CLOSED_REASON: `No se completó la dependencia ${dependency}; se requiere evidencia válida antes de continuar.` })
}
export class RevenueDependencyErrorV1 extends Error {
  readonly PROVIDER_REQUEST_ID?: string
  readonly ERROR_CODE: string
  readonly DEPENDENCY_STAGE: RevenueDependencyStageV1
  readonly TRACE_ID: string
  readonly FAIL_CLOSED_REASON: string
  constructor(code: string, stage: RevenueDependencyStageV1, traceId?: string, providerRequestId?: string) {
    super(code)
    const details = revenueFailureV1(new Error(code), stage, "SELLER_OS_TOOL_FAILED_CLOSED", traceId)
    if (providerRequestId && /^req_[a-zA-Z0-9_-]{8,120}$/.test(providerRequestId)) this.PROVIDER_REQUEST_ID = providerRequestId
    this.ERROR_CODE = details.ERROR_CODE
    this.DEPENDENCY_STAGE = details.DEPENDENCY_STAGE
    this.TRACE_ID = details.TRACE_ID
    this.FAIL_CLOSED_REASON = details.FAIL_CLOSED_REASON
  }
}
